/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as WorkspaceTransactionsIndexRouteImport } from './routes/_workspace/transactions/index'
import { Route as WorkspaceSuppliersIndexRouteImport } from './routes/_workspace/suppliers/index'
import { Route as WorkspaceSellabilityIndexRouteImport } from './routes/_workspace/sellability/index'
import { Route as WorkspaceResourcesIndexRouteImport } from './routes/_workspace/resources/index'
import { Route as WorkspaceQuotesIndexRouteImport } from './routes/_workspace/quotes/index'
import { Route as WorkspacePropertyGroupsIndexRouteImport } from './routes/_workspace/property-groups/index'
import { Route as WorkspacePropertiesIndexRouteImport } from './routes/_workspace/properties/index'
import { Route as WorkspaceProductsIndexRouteImport } from './routes/_workspace/products/index'
import { Route as WorkspacePeopleIndexRouteImport } from './routes/_workspace/people/index'
import { Route as WorkspaceOrganizationsIndexRouteImport } from './routes/_workspace/organizations/index'
import { Route as WorkspaceOpportunitiesIndexRouteImport } from './routes/_workspace/opportunities/index'
import { Route as WorkspaceMarketsIndexRouteImport } from './routes/_workspace/markets/index'
import { Route as WorkspaceIdentityIndexRouteImport } from './routes/_workspace/identity/index'
import { Route as WorkspaceHospitalityIndexRouteImport } from './routes/_workspace/hospitality/index'
import { Route as WorkspaceGroundIndexRouteImport } from './routes/_workspace/ground/index'
import { Route as WorkspaceFinanceIndexRouteImport } from './routes/_workspace/finance/index'
import { Route as WorkspaceFacilitiesIndexRouteImport } from './routes/_workspace/facilities/index'
import { Route as WorkspaceExtrasIndexRouteImport } from './routes/_workspace/extras/index'
import { Route as WorkspaceExternalRefsIndexRouteImport } from './routes/_workspace/external-refs/index'
import { Route as WorkspaceDistributionIndexRouteImport } from './routes/_workspace/distribution/index'
import { Route as WorkspaceBookingsIndexRouteImport } from './routes/_workspace/bookings/index'
import { Route as WorkspaceBookingRequirementsIndexRouteImport } from './routes/_workspace/booking-requirements/index'
import { Route as WorkspaceAvailabilityIndexRouteImport } from './routes/_workspace/availability/index'
import { Route as WorkspaceActivitiesIndexRouteImport } from './routes/_workspace/activities/index'
import { Route as WorkspaceSuppliersIdRouteImport } from './routes/_workspace/suppliers/$id'
import { Route as WorkspaceSettingsTeamRouteImport } from './routes/_workspace/settings/team'
import { Route as WorkspaceResourcesIdRouteImport } from './routes/_workspace/resources/$id'
import { Route as WorkspaceQuotesIdRouteImport } from './routes/_workspace/quotes/$id'
import { Route as WorkspacePropertyGroupsIdRouteImport } from './routes/_workspace/property-groups/$id'
import { Route as WorkspacePropertiesIdRouteImport } from './routes/_workspace/properties/$id'
import { Route as WorkspaceProductsIdRouteImport } from './routes/_workspace/products/$id'
import { Route as WorkspacePeopleIdRouteImport } from './routes/_workspace/people/$id'
import { Route as WorkspaceOrganizationsIdRouteImport } from './routes/_workspace/organizations/$id'
import { Route as WorkspaceOpportunitiesIdRouteImport } from './routes/_workspace/opportunities/$id'
import { Route as WorkspaceFacilitiesIdRouteImport } from './routes/_workspace/facilities/$id'
import { Route as WorkspaceDistributionIdRouteImport } from './routes/_workspace/distribution/$id'
import { Route as WorkspaceBookingsIdRouteImport } from './routes/_workspace/bookings/$id'
import { Route as WorkspaceAvailabilityIdRouteImport } from './routes/_workspace/availability/$id'
import { Route as WorkspaceLegalTemplatesIndexRouteImport } from './routes/_workspace/legal/templates/index'
import { Route as WorkspaceLegalPoliciesIndexRouteImport } from './routes/_workspace/legal/policies/index'
import { Route as WorkspaceLegalNumberSeriesIndexRouteImport } from './routes/_workspace/legal/number-series/index'
import { Route as WorkspaceLegalContractsIndexRouteImport } from './routes/_workspace/legal/contracts/index'
import { Route as WorkspaceSettingsPricingSchedulesRouteImport } from './routes/_workspace/settings/pricing/schedules'
import { Route as WorkspaceSettingsPricingPickupPriceRulesRouteImport } from './routes/_workspace/settings/pricing/pickup-price-rules'
import { Route as WorkspaceSettingsPricingOptionUnitTiersRouteImport } from './routes/_workspace/settings/pricing/option-unit-tiers'
import { Route as WorkspaceSettingsPricingOptionUnitPriceRulesRouteImport } from './routes/_workspace/settings/pricing/option-unit-price-rules'
import { Route as WorkspaceSettingsPricingOptionStartTimeRulesRouteImport } from './routes/_workspace/settings/pricing/option-start-time-rules'
import { Route as WorkspaceSettingsPricingOptionPriceRulesRouteImport } from './routes/_workspace/settings/pricing/option-price-rules'
import { Route as WorkspaceSettingsPricingExtraPriceRulesRouteImport } from './routes/_workspace/settings/pricing/extra-price-rules'
import { Route as WorkspaceSettingsPricingDropoffPriceRulesRouteImport } from './routes/_workspace/settings/pricing/dropoff-price-rules'
import { Route as WorkspaceSettingsPricingCategoryDependenciesRouteImport } from './routes/_workspace/settings/pricing/category-dependencies'
import { Route as WorkspaceSettingsPricingCategoriesRouteImport } from './routes/_workspace/settings/pricing/categories'
import { Route as WorkspaceSettingsPricingCatalogsRouteImport } from './routes/_workspace/settings/pricing/catalogs'
import { Route as WorkspaceSettingsPricingCancellationPoliciesRouteImport } from './routes/_workspace/settings/pricing/cancellation-policies'
import { Route as WorkspaceResourcesPoolsIdRouteImport } from './routes/_workspace/resources/pools/$id'
import { Route as WorkspaceResourcesAssignmentsIdRouteImport } from './routes/_workspace/resources/assignments/$id'
import { Route as WorkspaceResourcesAllocationsIdRouteImport } from './routes/_workspace/resources/allocations/$id'
import { Route as WorkspaceLegalPoliciesIdRouteImport } from './routes/_workspace/legal/policies/$id'
import { Route as WorkspaceLegalContractsIdRouteImport } from './routes/_workspace/legal/contracts/$id'
import { Route as WorkspaceFinanceInvoicesIdRouteImport } from './routes/_workspace/finance/invoices/$id'
import { Route as WorkspaceDistributionWebhookEventsIdRouteImport } from './routes/_workspace/distribution/webhook-events/$id'
import { Route as WorkspaceDistributionMappingsIdRouteImport } from './routes/_workspace/distribution/mappings/$id'
import { Route as WorkspaceDistributionContractsIdRouteImport } from './routes/_workspace/distribution/contracts/$id'
import { Route as WorkspaceDistributionCommissionRulesIdRouteImport } from './routes/_workspace/distribution/commission-rules/$id'
import { Route as WorkspaceDistributionBookingLinksIdRouteImport } from './routes/_workspace/distribution/booking-links/$id'
import { Route as WorkspaceAvailabilityStartTimesIdRouteImport } from './routes/_workspace/availability/start-times/$id'
import { Route as WorkspaceAvailabilityRulesIdRouteImport } from './routes/_workspace/availability/rules/$id'

const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => authRouteRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceTransactionsIndexRoute =
  WorkspaceTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceSuppliersIndexRoute = WorkspaceSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSellabilityIndexRoute =
  WorkspaceSellabilityIndexRouteImport.update({
    id: '/sellability/',
    path: '/sellability/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesIndexRoute = WorkspaceResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceQuotesIndexRoute = WorkspaceQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePropertyGroupsIndexRoute =
  WorkspacePropertyGroupsIndexRouteImport.update({
    id: '/property-groups/',
    path: '/property-groups/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspacePropertiesIndexRoute =
  WorkspacePropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceProductsIndexRoute = WorkspaceProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePeopleIndexRoute = WorkspacePeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOrganizationsIndexRoute =
  WorkspaceOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceOpportunitiesIndexRoute =
  WorkspaceOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceMarketsIndexRoute = WorkspaceMarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceIdentityIndexRoute = WorkspaceIdentityIndexRouteImport.update({
  id: '/identity/',
  path: '/identity/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceHospitalityIndexRoute =
  WorkspaceHospitalityIndexRouteImport.update({
    id: '/hospitality/',
    path: '/hospitality/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceGroundIndexRoute = WorkspaceGroundIndexRouteImport.update({
  id: '/ground/',
  path: '/ground/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceFinanceIndexRoute = WorkspaceFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceFacilitiesIndexRoute =
  WorkspaceFacilitiesIndexRouteImport.update({
    id: '/facilities/',
    path: '/facilities/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceExtrasIndexRoute = WorkspaceExtrasIndexRouteImport.update({
  id: '/extras/',
  path: '/extras/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceExternalRefsIndexRoute =
  WorkspaceExternalRefsIndexRouteImport.update({
    id: '/external-refs/',
    path: '/external-refs/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionIndexRoute =
  WorkspaceDistributionIndexRouteImport.update({
    id: '/distribution/',
    path: '/distribution/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceBookingsIndexRoute = WorkspaceBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceBookingRequirementsIndexRoute =
  WorkspaceBookingRequirementsIndexRouteImport.update({
    id: '/booking-requirements/',
    path: '/booking-requirements/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityIndexRoute =
  WorkspaceAvailabilityIndexRouteImport.update({
    id: '/availability/',
    path: '/availability/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceActivitiesIndexRoute =
  WorkspaceActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceSuppliersIdRoute = WorkspaceSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsTeamRoute = WorkspaceSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceResourcesIdRoute = WorkspaceResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceQuotesIdRoute = WorkspaceQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePropertyGroupsIdRoute =
  WorkspacePropertyGroupsIdRouteImport.update({
    id: '/property-groups/$id',
    path: '/property-groups/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspacePropertiesIdRoute = WorkspacePropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProductsIdRoute = WorkspaceProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePeopleIdRoute = WorkspacePeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOrganizationsIdRoute =
  WorkspaceOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceOpportunitiesIdRoute =
  WorkspaceOpportunitiesIdRouteImport.update({
    id: '/opportunities/$id',
    path: '/opportunities/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFacilitiesIdRoute = WorkspaceFacilitiesIdRouteImport.update({
  id: '/facilities/$id',
  path: '/facilities/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceDistributionIdRoute = WorkspaceDistributionIdRouteImport.update({
  id: '/distribution/$id',
  path: '/distribution/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceBookingsIdRoute = WorkspaceBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAvailabilityIdRoute = WorkspaceAvailabilityIdRouteImport.update({
  id: '/availability/$id',
  path: '/availability/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceLegalTemplatesIndexRoute =
  WorkspaceLegalTemplatesIndexRouteImport.update({
    id: '/legal/templates/',
    path: '/legal/templates/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalPoliciesIndexRoute =
  WorkspaceLegalPoliciesIndexRouteImport.update({
    id: '/legal/policies/',
    path: '/legal/policies/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalNumberSeriesIndexRoute =
  WorkspaceLegalNumberSeriesIndexRouteImport.update({
    id: '/legal/number-series/',
    path: '/legal/number-series/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalContractsIndexRoute =
  WorkspaceLegalContractsIndexRouteImport.update({
    id: '/legal/contracts/',
    path: '/legal/contracts/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceSettingsPricingSchedulesRoute =
  WorkspaceSettingsPricingSchedulesRouteImport.update({
    id: '/pricing/schedules',
    path: '/pricing/schedules',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingPickupPriceRulesRoute =
  WorkspaceSettingsPricingPickupPriceRulesRouteImport.update({
    id: '/pricing/pickup-price-rules',
    path: '/pricing/pickup-price-rules',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingOptionUnitTiersRoute =
  WorkspaceSettingsPricingOptionUnitTiersRouteImport.update({
    id: '/pricing/option-unit-tiers',
    path: '/pricing/option-unit-tiers',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingOptionUnitPriceRulesRoute =
  WorkspaceSettingsPricingOptionUnitPriceRulesRouteImport.update({
    id: '/pricing/option-unit-price-rules',
    path: '/pricing/option-unit-price-rules',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingOptionStartTimeRulesRoute =
  WorkspaceSettingsPricingOptionStartTimeRulesRouteImport.update({
    id: '/pricing/option-start-time-rules',
    path: '/pricing/option-start-time-rules',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingOptionPriceRulesRoute =
  WorkspaceSettingsPricingOptionPriceRulesRouteImport.update({
    id: '/pricing/option-price-rules',
    path: '/pricing/option-price-rules',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingExtraPriceRulesRoute =
  WorkspaceSettingsPricingExtraPriceRulesRouteImport.update({
    id: '/pricing/extra-price-rules',
    path: '/pricing/extra-price-rules',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingDropoffPriceRulesRoute =
  WorkspaceSettingsPricingDropoffPriceRulesRouteImport.update({
    id: '/pricing/dropoff-price-rules',
    path: '/pricing/dropoff-price-rules',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingCategoryDependenciesRoute =
  WorkspaceSettingsPricingCategoryDependenciesRouteImport.update({
    id: '/pricing/category-dependencies',
    path: '/pricing/category-dependencies',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingCategoriesRoute =
  WorkspaceSettingsPricingCategoriesRouteImport.update({
    id: '/pricing/categories',
    path: '/pricing/categories',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingCatalogsRoute =
  WorkspaceSettingsPricingCatalogsRouteImport.update({
    id: '/pricing/catalogs',
    path: '/pricing/catalogs',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingCancellationPoliciesRoute =
  WorkspaceSettingsPricingCancellationPoliciesRouteImport.update({
    id: '/pricing/cancellation-policies',
    path: '/pricing/cancellation-policies',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceResourcesPoolsIdRoute =
  WorkspaceResourcesPoolsIdRouteImport.update({
    id: '/resources/pools/$id',
    path: '/resources/pools/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAssignmentsIdRoute =
  WorkspaceResourcesAssignmentsIdRouteImport.update({
    id: '/resources/assignments/$id',
    path: '/resources/assignments/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAllocationsIdRoute =
  WorkspaceResourcesAllocationsIdRouteImport.update({
    id: '/resources/allocations/$id',
    path: '/resources/allocations/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalPoliciesIdRoute =
  WorkspaceLegalPoliciesIdRouteImport.update({
    id: '/legal/policies/$id',
    path: '/legal/policies/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLegalContractsIdRoute =
  WorkspaceLegalContractsIdRouteImport.update({
    id: '/legal/contracts/$id',
    path: '/legal/contracts/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceInvoicesIdRoute =
  WorkspaceFinanceInvoicesIdRouteImport.update({
    id: '/finance/invoices/$id',
    path: '/finance/invoices/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionWebhookEventsIdRoute =
  WorkspaceDistributionWebhookEventsIdRouteImport.update({
    id: '/distribution/webhook-events/$id',
    path: '/distribution/webhook-events/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionMappingsIdRoute =
  WorkspaceDistributionMappingsIdRouteImport.update({
    id: '/distribution/mappings/$id',
    path: '/distribution/mappings/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionContractsIdRoute =
  WorkspaceDistributionContractsIdRouteImport.update({
    id: '/distribution/contracts/$id',
    path: '/distribution/contracts/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionCommissionRulesIdRoute =
  WorkspaceDistributionCommissionRulesIdRouteImport.update({
    id: '/distribution/commission-rules/$id',
    path: '/distribution/commission-rules/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionBookingLinksIdRoute =
  WorkspaceDistributionBookingLinksIdRouteImport.update({
    id: '/distribution/booking-links/$id',
    path: '/distribution/booking-links/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityStartTimesIdRoute =
  WorkspaceAvailabilityStartTimesIdRouteImport.update({
    id: '/availability/start-times/$id',
    path: '/availability/start-times/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityRulesIdRoute =
  WorkspaceAvailabilityRulesIdRouteImport.update({
    id: '/availability/rules/$id',
    path: '/availability/rules/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/distribution/$id': typeof WorkspaceDistributionIdRoute
  '/facilities/$id': typeof WorkspaceFacilitiesIdRoute
  '/opportunities/$id': typeof WorkspaceOpportunitiesIdRoute
  '/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/people/$id': typeof WorkspacePeopleIdRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/properties/$id': typeof WorkspacePropertiesIdRoute
  '/property-groups/$id': typeof WorkspacePropertyGroupsIdRoute
  '/quotes/$id': typeof WorkspaceQuotesIdRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/settings/team': typeof WorkspaceSettingsTeamRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/activities/': typeof WorkspaceActivitiesIndexRoute
  '/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/booking-requirements/': typeof WorkspaceBookingRequirementsIndexRoute
  '/bookings/': typeof WorkspaceBookingsIndexRoute
  '/distribution/': typeof WorkspaceDistributionIndexRoute
  '/external-refs/': typeof WorkspaceExternalRefsIndexRoute
  '/extras/': typeof WorkspaceExtrasIndexRoute
  '/facilities/': typeof WorkspaceFacilitiesIndexRoute
  '/finance/': typeof WorkspaceFinanceIndexRoute
  '/ground/': typeof WorkspaceGroundIndexRoute
  '/hospitality/': typeof WorkspaceHospitalityIndexRoute
  '/identity/': typeof WorkspaceIdentityIndexRoute
  '/markets/': typeof WorkspaceMarketsIndexRoute
  '/opportunities/': typeof WorkspaceOpportunitiesIndexRoute
  '/organizations/': typeof WorkspaceOrganizationsIndexRoute
  '/people/': typeof WorkspacePeopleIndexRoute
  '/products/': typeof WorkspaceProductsIndexRoute
  '/properties/': typeof WorkspacePropertiesIndexRoute
  '/property-groups/': typeof WorkspacePropertyGroupsIndexRoute
  '/quotes/': typeof WorkspaceQuotesIndexRoute
  '/resources/': typeof WorkspaceResourcesIndexRoute
  '/sellability/': typeof WorkspaceSellabilityIndexRoute
  '/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/transactions/': typeof WorkspaceTransactionsIndexRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/distribution/booking-links/$id': typeof WorkspaceDistributionBookingLinksIdRoute
  '/distribution/commission-rules/$id': typeof WorkspaceDistributionCommissionRulesIdRoute
  '/distribution/contracts/$id': typeof WorkspaceDistributionContractsIdRoute
  '/distribution/mappings/$id': typeof WorkspaceDistributionMappingsIdRoute
  '/distribution/webhook-events/$id': typeof WorkspaceDistributionWebhookEventsIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/legal/contracts/$id': typeof WorkspaceLegalContractsIdRoute
  '/legal/policies/$id': typeof WorkspaceLegalPoliciesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/settings/pricing/cancellation-policies': typeof WorkspaceSettingsPricingCancellationPoliciesRoute
  '/settings/pricing/catalogs': typeof WorkspaceSettingsPricingCatalogsRoute
  '/settings/pricing/categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/pricing/category-dependencies': typeof WorkspaceSettingsPricingCategoryDependenciesRoute
  '/settings/pricing/dropoff-price-rules': typeof WorkspaceSettingsPricingDropoffPriceRulesRoute
  '/settings/pricing/extra-price-rules': typeof WorkspaceSettingsPricingExtraPriceRulesRoute
  '/settings/pricing/option-price-rules': typeof WorkspaceSettingsPricingOptionPriceRulesRoute
  '/settings/pricing/option-start-time-rules': typeof WorkspaceSettingsPricingOptionStartTimeRulesRoute
  '/settings/pricing/option-unit-price-rules': typeof WorkspaceSettingsPricingOptionUnitPriceRulesRoute
  '/settings/pricing/option-unit-tiers': typeof WorkspaceSettingsPricingOptionUnitTiersRoute
  '/settings/pricing/pickup-price-rules': typeof WorkspaceSettingsPricingPickupPriceRulesRoute
  '/settings/pricing/schedules': typeof WorkspaceSettingsPricingSchedulesRoute
  '/legal/contracts/': typeof WorkspaceLegalContractsIndexRoute
  '/legal/number-series/': typeof WorkspaceLegalNumberSeriesIndexRoute
  '/legal/policies/': typeof WorkspaceLegalPoliciesIndexRoute
  '/legal/templates/': typeof WorkspaceLegalTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof WorkspaceIndexRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/distribution/$id': typeof WorkspaceDistributionIdRoute
  '/facilities/$id': typeof WorkspaceFacilitiesIdRoute
  '/opportunities/$id': typeof WorkspaceOpportunitiesIdRoute
  '/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/people/$id': typeof WorkspacePeopleIdRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/properties/$id': typeof WorkspacePropertiesIdRoute
  '/property-groups/$id': typeof WorkspacePropertyGroupsIdRoute
  '/quotes/$id': typeof WorkspaceQuotesIdRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/settings/team': typeof WorkspaceSettingsTeamRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/activities': typeof WorkspaceActivitiesIndexRoute
  '/availability': typeof WorkspaceAvailabilityIndexRoute
  '/booking-requirements': typeof WorkspaceBookingRequirementsIndexRoute
  '/bookings': typeof WorkspaceBookingsIndexRoute
  '/distribution': typeof WorkspaceDistributionIndexRoute
  '/external-refs': typeof WorkspaceExternalRefsIndexRoute
  '/extras': typeof WorkspaceExtrasIndexRoute
  '/facilities': typeof WorkspaceFacilitiesIndexRoute
  '/finance': typeof WorkspaceFinanceIndexRoute
  '/ground': typeof WorkspaceGroundIndexRoute
  '/hospitality': typeof WorkspaceHospitalityIndexRoute
  '/identity': typeof WorkspaceIdentityIndexRoute
  '/markets': typeof WorkspaceMarketsIndexRoute
  '/opportunities': typeof WorkspaceOpportunitiesIndexRoute
  '/organizations': typeof WorkspaceOrganizationsIndexRoute
  '/people': typeof WorkspacePeopleIndexRoute
  '/products': typeof WorkspaceProductsIndexRoute
  '/properties': typeof WorkspacePropertiesIndexRoute
  '/property-groups': typeof WorkspacePropertyGroupsIndexRoute
  '/quotes': typeof WorkspaceQuotesIndexRoute
  '/resources': typeof WorkspaceResourcesIndexRoute
  '/sellability': typeof WorkspaceSellabilityIndexRoute
  '/suppliers': typeof WorkspaceSuppliersIndexRoute
  '/transactions': typeof WorkspaceTransactionsIndexRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/distribution/booking-links/$id': typeof WorkspaceDistributionBookingLinksIdRoute
  '/distribution/commission-rules/$id': typeof WorkspaceDistributionCommissionRulesIdRoute
  '/distribution/contracts/$id': typeof WorkspaceDistributionContractsIdRoute
  '/distribution/mappings/$id': typeof WorkspaceDistributionMappingsIdRoute
  '/distribution/webhook-events/$id': typeof WorkspaceDistributionWebhookEventsIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/legal/contracts/$id': typeof WorkspaceLegalContractsIdRoute
  '/legal/policies/$id': typeof WorkspaceLegalPoliciesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/settings/pricing/cancellation-policies': typeof WorkspaceSettingsPricingCancellationPoliciesRoute
  '/settings/pricing/catalogs': typeof WorkspaceSettingsPricingCatalogsRoute
  '/settings/pricing/categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/pricing/category-dependencies': typeof WorkspaceSettingsPricingCategoryDependenciesRoute
  '/settings/pricing/dropoff-price-rules': typeof WorkspaceSettingsPricingDropoffPriceRulesRoute
  '/settings/pricing/extra-price-rules': typeof WorkspaceSettingsPricingExtraPriceRulesRoute
  '/settings/pricing/option-price-rules': typeof WorkspaceSettingsPricingOptionPriceRulesRoute
  '/settings/pricing/option-start-time-rules': typeof WorkspaceSettingsPricingOptionStartTimeRulesRoute
  '/settings/pricing/option-unit-price-rules': typeof WorkspaceSettingsPricingOptionUnitPriceRulesRoute
  '/settings/pricing/option-unit-tiers': typeof WorkspaceSettingsPricingOptionUnitTiersRoute
  '/settings/pricing/pickup-price-rules': typeof WorkspaceSettingsPricingPickupPriceRulesRoute
  '/settings/pricing/schedules': typeof WorkspaceSettingsPricingSchedulesRoute
  '/legal/contracts': typeof WorkspaceLegalContractsIndexRoute
  '/legal/number-series': typeof WorkspaceLegalNumberSeriesIndexRoute
  '/legal/policies': typeof WorkspaceLegalPoliciesIndexRoute
  '/legal/templates': typeof WorkspaceLegalTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/_workspace/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/_workspace/distribution/$id': typeof WorkspaceDistributionIdRoute
  '/_workspace/facilities/$id': typeof WorkspaceFacilitiesIdRoute
  '/_workspace/opportunities/$id': typeof WorkspaceOpportunitiesIdRoute
  '/_workspace/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/_workspace/people/$id': typeof WorkspacePeopleIdRoute
  '/_workspace/products/$id': typeof WorkspaceProductsIdRoute
  '/_workspace/properties/$id': typeof WorkspacePropertiesIdRoute
  '/_workspace/property-groups/$id': typeof WorkspacePropertyGroupsIdRoute
  '/_workspace/quotes/$id': typeof WorkspaceQuotesIdRoute
  '/_workspace/resources/$id': typeof WorkspaceResourcesIdRoute
  '/_workspace/settings/team': typeof WorkspaceSettingsTeamRoute
  '/_workspace/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/_workspace/activities/': typeof WorkspaceActivitiesIndexRoute
  '/_workspace/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/_workspace/booking-requirements/': typeof WorkspaceBookingRequirementsIndexRoute
  '/_workspace/bookings/': typeof WorkspaceBookingsIndexRoute
  '/_workspace/distribution/': typeof WorkspaceDistributionIndexRoute
  '/_workspace/external-refs/': typeof WorkspaceExternalRefsIndexRoute
  '/_workspace/extras/': typeof WorkspaceExtrasIndexRoute
  '/_workspace/facilities/': typeof WorkspaceFacilitiesIndexRoute
  '/_workspace/finance/': typeof WorkspaceFinanceIndexRoute
  '/_workspace/ground/': typeof WorkspaceGroundIndexRoute
  '/_workspace/hospitality/': typeof WorkspaceHospitalityIndexRoute
  '/_workspace/identity/': typeof WorkspaceIdentityIndexRoute
  '/_workspace/markets/': typeof WorkspaceMarketsIndexRoute
  '/_workspace/opportunities/': typeof WorkspaceOpportunitiesIndexRoute
  '/_workspace/organizations/': typeof WorkspaceOrganizationsIndexRoute
  '/_workspace/people/': typeof WorkspacePeopleIndexRoute
  '/_workspace/products/': typeof WorkspaceProductsIndexRoute
  '/_workspace/properties/': typeof WorkspacePropertiesIndexRoute
  '/_workspace/property-groups/': typeof WorkspacePropertyGroupsIndexRoute
  '/_workspace/quotes/': typeof WorkspaceQuotesIndexRoute
  '/_workspace/resources/': typeof WorkspaceResourcesIndexRoute
  '/_workspace/sellability/': typeof WorkspaceSellabilityIndexRoute
  '/_workspace/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/_workspace/transactions/': typeof WorkspaceTransactionsIndexRoute
  '/_workspace/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/_workspace/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/_workspace/distribution/booking-links/$id': typeof WorkspaceDistributionBookingLinksIdRoute
  '/_workspace/distribution/commission-rules/$id': typeof WorkspaceDistributionCommissionRulesIdRoute
  '/_workspace/distribution/contracts/$id': typeof WorkspaceDistributionContractsIdRoute
  '/_workspace/distribution/mappings/$id': typeof WorkspaceDistributionMappingsIdRoute
  '/_workspace/distribution/webhook-events/$id': typeof WorkspaceDistributionWebhookEventsIdRoute
  '/_workspace/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/_workspace/legal/contracts/$id': typeof WorkspaceLegalContractsIdRoute
  '/_workspace/legal/policies/$id': typeof WorkspaceLegalPoliciesIdRoute
  '/_workspace/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/_workspace/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/_workspace/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/_workspace/settings/pricing/cancellation-policies': typeof WorkspaceSettingsPricingCancellationPoliciesRoute
  '/_workspace/settings/pricing/catalogs': typeof WorkspaceSettingsPricingCatalogsRoute
  '/_workspace/settings/pricing/categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/_workspace/settings/pricing/category-dependencies': typeof WorkspaceSettingsPricingCategoryDependenciesRoute
  '/_workspace/settings/pricing/dropoff-price-rules': typeof WorkspaceSettingsPricingDropoffPriceRulesRoute
  '/_workspace/settings/pricing/extra-price-rules': typeof WorkspaceSettingsPricingExtraPriceRulesRoute
  '/_workspace/settings/pricing/option-price-rules': typeof WorkspaceSettingsPricingOptionPriceRulesRoute
  '/_workspace/settings/pricing/option-start-time-rules': typeof WorkspaceSettingsPricingOptionStartTimeRulesRoute
  '/_workspace/settings/pricing/option-unit-price-rules': typeof WorkspaceSettingsPricingOptionUnitPriceRulesRoute
  '/_workspace/settings/pricing/option-unit-tiers': typeof WorkspaceSettingsPricingOptionUnitTiersRoute
  '/_workspace/settings/pricing/pickup-price-rules': typeof WorkspaceSettingsPricingPickupPriceRulesRoute
  '/_workspace/settings/pricing/schedules': typeof WorkspaceSettingsPricingSchedulesRoute
  '/_workspace/legal/contracts/': typeof WorkspaceLegalContractsIndexRoute
  '/_workspace/legal/number-series/': typeof WorkspaceLegalNumberSeriesIndexRoute
  '/_workspace/legal/policies/': typeof WorkspaceLegalPoliciesIndexRoute
  '/_workspace/legal/templates/': typeof WorkspaceLegalTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/availability/$id'
    | '/bookings/$id'
    | '/distribution/$id'
    | '/facilities/$id'
    | '/opportunities/$id'
    | '/organizations/$id'
    | '/people/$id'
    | '/products/$id'
    | '/properties/$id'
    | '/property-groups/$id'
    | '/quotes/$id'
    | '/resources/$id'
    | '/settings/team'
    | '/suppliers/$id'
    | '/activities/'
    | '/availability/'
    | '/booking-requirements/'
    | '/bookings/'
    | '/distribution/'
    | '/external-refs/'
    | '/extras/'
    | '/facilities/'
    | '/finance/'
    | '/ground/'
    | '/hospitality/'
    | '/identity/'
    | '/markets/'
    | '/opportunities/'
    | '/organizations/'
    | '/people/'
    | '/products/'
    | '/properties/'
    | '/property-groups/'
    | '/quotes/'
    | '/resources/'
    | '/sellability/'
    | '/suppliers/'
    | '/transactions/'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/distribution/booking-links/$id'
    | '/distribution/commission-rules/$id'
    | '/distribution/contracts/$id'
    | '/distribution/mappings/$id'
    | '/distribution/webhook-events/$id'
    | '/finance/invoices/$id'
    | '/legal/contracts/$id'
    | '/legal/policies/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
    | '/settings/pricing/cancellation-policies'
    | '/settings/pricing/catalogs'
    | '/settings/pricing/categories'
    | '/settings/pricing/category-dependencies'
    | '/settings/pricing/dropoff-price-rules'
    | '/settings/pricing/extra-price-rules'
    | '/settings/pricing/option-price-rules'
    | '/settings/pricing/option-start-time-rules'
    | '/settings/pricing/option-unit-price-rules'
    | '/settings/pricing/option-unit-tiers'
    | '/settings/pricing/pickup-price-rules'
    | '/settings/pricing/schedules'
    | '/legal/contracts/'
    | '/legal/number-series/'
    | '/legal/policies/'
    | '/legal/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/'
    | '/availability/$id'
    | '/bookings/$id'
    | '/distribution/$id'
    | '/facilities/$id'
    | '/opportunities/$id'
    | '/organizations/$id'
    | '/people/$id'
    | '/products/$id'
    | '/properties/$id'
    | '/property-groups/$id'
    | '/quotes/$id'
    | '/resources/$id'
    | '/settings/team'
    | '/suppliers/$id'
    | '/activities'
    | '/availability'
    | '/booking-requirements'
    | '/bookings'
    | '/distribution'
    | '/external-refs'
    | '/extras'
    | '/facilities'
    | '/finance'
    | '/ground'
    | '/hospitality'
    | '/identity'
    | '/markets'
    | '/opportunities'
    | '/organizations'
    | '/people'
    | '/products'
    | '/properties'
    | '/property-groups'
    | '/quotes'
    | '/resources'
    | '/sellability'
    | '/suppliers'
    | '/transactions'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/distribution/booking-links/$id'
    | '/distribution/commission-rules/$id'
    | '/distribution/contracts/$id'
    | '/distribution/mappings/$id'
    | '/distribution/webhook-events/$id'
    | '/finance/invoices/$id'
    | '/legal/contracts/$id'
    | '/legal/policies/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
    | '/settings/pricing/cancellation-policies'
    | '/settings/pricing/catalogs'
    | '/settings/pricing/categories'
    | '/settings/pricing/category-dependencies'
    | '/settings/pricing/dropoff-price-rules'
    | '/settings/pricing/extra-price-rules'
    | '/settings/pricing/option-price-rules'
    | '/settings/pricing/option-start-time-rules'
    | '/settings/pricing/option-unit-price-rules'
    | '/settings/pricing/option-unit-tiers'
    | '/settings/pricing/pickup-price-rules'
    | '/settings/pricing/schedules'
    | '/legal/contracts'
    | '/legal/number-series'
    | '/legal/policies'
    | '/legal/templates'
  id:
    | '__root__'
    | '/(auth)'
    | '/_workspace'
    | '/_workspace/settings'
    | '/(auth)/accept-invitation'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/_workspace/'
    | '/_workspace/availability/$id'
    | '/_workspace/bookings/$id'
    | '/_workspace/distribution/$id'
    | '/_workspace/facilities/$id'
    | '/_workspace/opportunities/$id'
    | '/_workspace/organizations/$id'
    | '/_workspace/people/$id'
    | '/_workspace/products/$id'
    | '/_workspace/properties/$id'
    | '/_workspace/property-groups/$id'
    | '/_workspace/quotes/$id'
    | '/_workspace/resources/$id'
    | '/_workspace/settings/team'
    | '/_workspace/suppliers/$id'
    | '/_workspace/activities/'
    | '/_workspace/availability/'
    | '/_workspace/booking-requirements/'
    | '/_workspace/bookings/'
    | '/_workspace/distribution/'
    | '/_workspace/external-refs/'
    | '/_workspace/extras/'
    | '/_workspace/facilities/'
    | '/_workspace/finance/'
    | '/_workspace/ground/'
    | '/_workspace/hospitality/'
    | '/_workspace/identity/'
    | '/_workspace/markets/'
    | '/_workspace/opportunities/'
    | '/_workspace/organizations/'
    | '/_workspace/people/'
    | '/_workspace/products/'
    | '/_workspace/properties/'
    | '/_workspace/property-groups/'
    | '/_workspace/quotes/'
    | '/_workspace/resources/'
    | '/_workspace/sellability/'
    | '/_workspace/suppliers/'
    | '/_workspace/transactions/'
    | '/_workspace/availability/rules/$id'
    | '/_workspace/availability/start-times/$id'
    | '/_workspace/distribution/booking-links/$id'
    | '/_workspace/distribution/commission-rules/$id'
    | '/_workspace/distribution/contracts/$id'
    | '/_workspace/distribution/mappings/$id'
    | '/_workspace/distribution/webhook-events/$id'
    | '/_workspace/finance/invoices/$id'
    | '/_workspace/legal/contracts/$id'
    | '/_workspace/legal/policies/$id'
    | '/_workspace/resources/allocations/$id'
    | '/_workspace/resources/assignments/$id'
    | '/_workspace/resources/pools/$id'
    | '/_workspace/settings/pricing/cancellation-policies'
    | '/_workspace/settings/pricing/catalogs'
    | '/_workspace/settings/pricing/categories'
    | '/_workspace/settings/pricing/category-dependencies'
    | '/_workspace/settings/pricing/dropoff-price-rules'
    | '/_workspace/settings/pricing/extra-price-rules'
    | '/_workspace/settings/pricing/option-price-rules'
    | '/_workspace/settings/pricing/option-start-time-rules'
    | '/_workspace/settings/pricing/option-unit-price-rules'
    | '/_workspace/settings/pricing/option-unit-tiers'
    | '/_workspace/settings/pricing/pickup-price-rules'
    | '/_workspace/settings/pricing/schedules'
    | '/_workspace/legal/contracts/'
    | '/_workspace/legal/number-series/'
    | '/_workspace/legal/policies/'
    | '/_workspace/legal/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/transactions/': {
      id: '/_workspace/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof WorkspaceTransactionsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/suppliers/': {
      id: '/_workspace/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof WorkspaceSuppliersIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/sellability/': {
      id: '/_workspace/sellability/'
      path: '/sellability'
      fullPath: '/sellability/'
      preLoaderRoute: typeof WorkspaceSellabilityIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/': {
      id: '/_workspace/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof WorkspaceResourcesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/quotes/': {
      id: '/_workspace/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof WorkspaceQuotesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/property-groups/': {
      id: '/_workspace/property-groups/'
      path: '/property-groups'
      fullPath: '/property-groups/'
      preLoaderRoute: typeof WorkspacePropertyGroupsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/properties/': {
      id: '/_workspace/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof WorkspacePropertiesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/': {
      id: '/_workspace/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof WorkspaceProductsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/people/': {
      id: '/_workspace/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof WorkspacePeopleIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/organizations/': {
      id: '/_workspace/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof WorkspaceOrganizationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/opportunities/': {
      id: '/_workspace/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof WorkspaceOpportunitiesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/markets/': {
      id: '/_workspace/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof WorkspaceMarketsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/identity/': {
      id: '/_workspace/identity/'
      path: '/identity'
      fullPath: '/identity/'
      preLoaderRoute: typeof WorkspaceIdentityIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/hospitality/': {
      id: '/_workspace/hospitality/'
      path: '/hospitality'
      fullPath: '/hospitality/'
      preLoaderRoute: typeof WorkspaceHospitalityIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/ground/': {
      id: '/_workspace/ground/'
      path: '/ground'
      fullPath: '/ground/'
      preLoaderRoute: typeof WorkspaceGroundIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/': {
      id: '/_workspace/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof WorkspaceFinanceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/facilities/': {
      id: '/_workspace/facilities/'
      path: '/facilities'
      fullPath: '/facilities/'
      preLoaderRoute: typeof WorkspaceFacilitiesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/extras/': {
      id: '/_workspace/extras/'
      path: '/extras'
      fullPath: '/extras/'
      preLoaderRoute: typeof WorkspaceExtrasIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/external-refs/': {
      id: '/_workspace/external-refs/'
      path: '/external-refs'
      fullPath: '/external-refs/'
      preLoaderRoute: typeof WorkspaceExternalRefsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/': {
      id: '/_workspace/distribution/'
      path: '/distribution'
      fullPath: '/distribution/'
      preLoaderRoute: typeof WorkspaceDistributionIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/': {
      id: '/_workspace/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof WorkspaceBookingsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/booking-requirements/': {
      id: '/_workspace/booking-requirements/'
      path: '/booking-requirements'
      fullPath: '/booking-requirements/'
      preLoaderRoute: typeof WorkspaceBookingRequirementsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/': {
      id: '/_workspace/availability/'
      path: '/availability'
      fullPath: '/availability/'
      preLoaderRoute: typeof WorkspaceAvailabilityIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/activities/': {
      id: '/_workspace/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof WorkspaceActivitiesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/suppliers/$id': {
      id: '/_workspace/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof WorkspaceSuppliersIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/team': {
      id: '/_workspace/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof WorkspaceSettingsTeamRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/resources/$id': {
      id: '/_workspace/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof WorkspaceResourcesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/quotes/$id': {
      id: '/_workspace/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof WorkspaceQuotesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/property-groups/$id': {
      id: '/_workspace/property-groups/$id'
      path: '/property-groups/$id'
      fullPath: '/property-groups/$id'
      preLoaderRoute: typeof WorkspacePropertyGroupsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/properties/$id': {
      id: '/_workspace/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof WorkspacePropertiesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/$id': {
      id: '/_workspace/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof WorkspaceProductsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/people/$id': {
      id: '/_workspace/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof WorkspacePeopleIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/organizations/$id': {
      id: '/_workspace/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof WorkspaceOrganizationsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/opportunities/$id': {
      id: '/_workspace/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof WorkspaceOpportunitiesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/facilities/$id': {
      id: '/_workspace/facilities/$id'
      path: '/facilities/$id'
      fullPath: '/facilities/$id'
      preLoaderRoute: typeof WorkspaceFacilitiesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/$id': {
      id: '/_workspace/distribution/$id'
      path: '/distribution/$id'
      fullPath: '/distribution/$id'
      preLoaderRoute: typeof WorkspaceDistributionIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/$id': {
      id: '/_workspace/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof WorkspaceBookingsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/$id': {
      id: '/_workspace/availability/$id'
      path: '/availability/$id'
      fullPath: '/availability/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/templates/': {
      id: '/_workspace/legal/templates/'
      path: '/legal/templates'
      fullPath: '/legal/templates/'
      preLoaderRoute: typeof WorkspaceLegalTemplatesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/policies/': {
      id: '/_workspace/legal/policies/'
      path: '/legal/policies'
      fullPath: '/legal/policies/'
      preLoaderRoute: typeof WorkspaceLegalPoliciesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/number-series/': {
      id: '/_workspace/legal/number-series/'
      path: '/legal/number-series'
      fullPath: '/legal/number-series/'
      preLoaderRoute: typeof WorkspaceLegalNumberSeriesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/contracts/': {
      id: '/_workspace/legal/contracts/'
      path: '/legal/contracts'
      fullPath: '/legal/contracts/'
      preLoaderRoute: typeof WorkspaceLegalContractsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/pricing/schedules': {
      id: '/_workspace/settings/pricing/schedules'
      path: '/pricing/schedules'
      fullPath: '/settings/pricing/schedules'
      preLoaderRoute: typeof WorkspaceSettingsPricingSchedulesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/pickup-price-rules': {
      id: '/_workspace/settings/pricing/pickup-price-rules'
      path: '/pricing/pickup-price-rules'
      fullPath: '/settings/pricing/pickup-price-rules'
      preLoaderRoute: typeof WorkspaceSettingsPricingPickupPriceRulesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/option-unit-tiers': {
      id: '/_workspace/settings/pricing/option-unit-tiers'
      path: '/pricing/option-unit-tiers'
      fullPath: '/settings/pricing/option-unit-tiers'
      preLoaderRoute: typeof WorkspaceSettingsPricingOptionUnitTiersRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/option-unit-price-rules': {
      id: '/_workspace/settings/pricing/option-unit-price-rules'
      path: '/pricing/option-unit-price-rules'
      fullPath: '/settings/pricing/option-unit-price-rules'
      preLoaderRoute: typeof WorkspaceSettingsPricingOptionUnitPriceRulesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/option-start-time-rules': {
      id: '/_workspace/settings/pricing/option-start-time-rules'
      path: '/pricing/option-start-time-rules'
      fullPath: '/settings/pricing/option-start-time-rules'
      preLoaderRoute: typeof WorkspaceSettingsPricingOptionStartTimeRulesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/option-price-rules': {
      id: '/_workspace/settings/pricing/option-price-rules'
      path: '/pricing/option-price-rules'
      fullPath: '/settings/pricing/option-price-rules'
      preLoaderRoute: typeof WorkspaceSettingsPricingOptionPriceRulesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/extra-price-rules': {
      id: '/_workspace/settings/pricing/extra-price-rules'
      path: '/pricing/extra-price-rules'
      fullPath: '/settings/pricing/extra-price-rules'
      preLoaderRoute: typeof WorkspaceSettingsPricingExtraPriceRulesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/dropoff-price-rules': {
      id: '/_workspace/settings/pricing/dropoff-price-rules'
      path: '/pricing/dropoff-price-rules'
      fullPath: '/settings/pricing/dropoff-price-rules'
      preLoaderRoute: typeof WorkspaceSettingsPricingDropoffPriceRulesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/category-dependencies': {
      id: '/_workspace/settings/pricing/category-dependencies'
      path: '/pricing/category-dependencies'
      fullPath: '/settings/pricing/category-dependencies'
      preLoaderRoute: typeof WorkspaceSettingsPricingCategoryDependenciesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/categories': {
      id: '/_workspace/settings/pricing/categories'
      path: '/pricing/categories'
      fullPath: '/settings/pricing/categories'
      preLoaderRoute: typeof WorkspaceSettingsPricingCategoriesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/catalogs': {
      id: '/_workspace/settings/pricing/catalogs'
      path: '/pricing/catalogs'
      fullPath: '/settings/pricing/catalogs'
      preLoaderRoute: typeof WorkspaceSettingsPricingCatalogsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing/cancellation-policies': {
      id: '/_workspace/settings/pricing/cancellation-policies'
      path: '/pricing/cancellation-policies'
      fullPath: '/settings/pricing/cancellation-policies'
      preLoaderRoute: typeof WorkspaceSettingsPricingCancellationPoliciesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/resources/pools/$id': {
      id: '/_workspace/resources/pools/$id'
      path: '/resources/pools/$id'
      fullPath: '/resources/pools/$id'
      preLoaderRoute: typeof WorkspaceResourcesPoolsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/assignments/$id': {
      id: '/_workspace/resources/assignments/$id'
      path: '/resources/assignments/$id'
      fullPath: '/resources/assignments/$id'
      preLoaderRoute: typeof WorkspaceResourcesAssignmentsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/allocations/$id': {
      id: '/_workspace/resources/allocations/$id'
      path: '/resources/allocations/$id'
      fullPath: '/resources/allocations/$id'
      preLoaderRoute: typeof WorkspaceResourcesAllocationsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/policies/$id': {
      id: '/_workspace/legal/policies/$id'
      path: '/legal/policies/$id'
      fullPath: '/legal/policies/$id'
      preLoaderRoute: typeof WorkspaceLegalPoliciesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/legal/contracts/$id': {
      id: '/_workspace/legal/contracts/$id'
      path: '/legal/contracts/$id'
      fullPath: '/legal/contracts/$id'
      preLoaderRoute: typeof WorkspaceLegalContractsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/invoices/$id': {
      id: '/_workspace/finance/invoices/$id'
      path: '/finance/invoices/$id'
      fullPath: '/finance/invoices/$id'
      preLoaderRoute: typeof WorkspaceFinanceInvoicesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/webhook-events/$id': {
      id: '/_workspace/distribution/webhook-events/$id'
      path: '/distribution/webhook-events/$id'
      fullPath: '/distribution/webhook-events/$id'
      preLoaderRoute: typeof WorkspaceDistributionWebhookEventsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/mappings/$id': {
      id: '/_workspace/distribution/mappings/$id'
      path: '/distribution/mappings/$id'
      fullPath: '/distribution/mappings/$id'
      preLoaderRoute: typeof WorkspaceDistributionMappingsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/contracts/$id': {
      id: '/_workspace/distribution/contracts/$id'
      path: '/distribution/contracts/$id'
      fullPath: '/distribution/contracts/$id'
      preLoaderRoute: typeof WorkspaceDistributionContractsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/commission-rules/$id': {
      id: '/_workspace/distribution/commission-rules/$id'
      path: '/distribution/commission-rules/$id'
      fullPath: '/distribution/commission-rules/$id'
      preLoaderRoute: typeof WorkspaceDistributionCommissionRulesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/booking-links/$id': {
      id: '/_workspace/distribution/booking-links/$id'
      path: '/distribution/booking-links/$id'
      fullPath: '/distribution/booking-links/$id'
      preLoaderRoute: typeof WorkspaceDistributionBookingLinksIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/start-times/$id': {
      id: '/_workspace/availability/start-times/$id'
      path: '/availability/start-times/$id'
      fullPath: '/availability/start-times/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityStartTimesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/rules/$id': {
      id: '/_workspace/availability/rules/$id'
      path: '/availability/rules/$id'
      fullPath: '/availability/rules/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityRulesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsTeamRoute: typeof WorkspaceSettingsTeamRoute
  WorkspaceSettingsPricingCancellationPoliciesRoute: typeof WorkspaceSettingsPricingCancellationPoliciesRoute
  WorkspaceSettingsPricingCatalogsRoute: typeof WorkspaceSettingsPricingCatalogsRoute
  WorkspaceSettingsPricingCategoriesRoute: typeof WorkspaceSettingsPricingCategoriesRoute
  WorkspaceSettingsPricingCategoryDependenciesRoute: typeof WorkspaceSettingsPricingCategoryDependenciesRoute
  WorkspaceSettingsPricingDropoffPriceRulesRoute: typeof WorkspaceSettingsPricingDropoffPriceRulesRoute
  WorkspaceSettingsPricingExtraPriceRulesRoute: typeof WorkspaceSettingsPricingExtraPriceRulesRoute
  WorkspaceSettingsPricingOptionPriceRulesRoute: typeof WorkspaceSettingsPricingOptionPriceRulesRoute
  WorkspaceSettingsPricingOptionStartTimeRulesRoute: typeof WorkspaceSettingsPricingOptionStartTimeRulesRoute
  WorkspaceSettingsPricingOptionUnitPriceRulesRoute: typeof WorkspaceSettingsPricingOptionUnitPriceRulesRoute
  WorkspaceSettingsPricingOptionUnitTiersRoute: typeof WorkspaceSettingsPricingOptionUnitTiersRoute
  WorkspaceSettingsPricingPickupPriceRulesRoute: typeof WorkspaceSettingsPricingPickupPriceRulesRoute
  WorkspaceSettingsPricingSchedulesRoute: typeof WorkspaceSettingsPricingSchedulesRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsTeamRoute: WorkspaceSettingsTeamRoute,
    WorkspaceSettingsPricingCancellationPoliciesRoute:
      WorkspaceSettingsPricingCancellationPoliciesRoute,
    WorkspaceSettingsPricingCatalogsRoute:
      WorkspaceSettingsPricingCatalogsRoute,
    WorkspaceSettingsPricingCategoriesRoute:
      WorkspaceSettingsPricingCategoriesRoute,
    WorkspaceSettingsPricingCategoryDependenciesRoute:
      WorkspaceSettingsPricingCategoryDependenciesRoute,
    WorkspaceSettingsPricingDropoffPriceRulesRoute:
      WorkspaceSettingsPricingDropoffPriceRulesRoute,
    WorkspaceSettingsPricingExtraPriceRulesRoute:
      WorkspaceSettingsPricingExtraPriceRulesRoute,
    WorkspaceSettingsPricingOptionPriceRulesRoute:
      WorkspaceSettingsPricingOptionPriceRulesRoute,
    WorkspaceSettingsPricingOptionStartTimeRulesRoute:
      WorkspaceSettingsPricingOptionStartTimeRulesRoute,
    WorkspaceSettingsPricingOptionUnitPriceRulesRoute:
      WorkspaceSettingsPricingOptionUnitPriceRulesRoute,
    WorkspaceSettingsPricingOptionUnitTiersRoute:
      WorkspaceSettingsPricingOptionUnitTiersRoute,
    WorkspaceSettingsPricingPickupPriceRulesRoute:
      WorkspaceSettingsPricingPickupPriceRulesRoute,
    WorkspaceSettingsPricingSchedulesRoute:
      WorkspaceSettingsPricingSchedulesRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceAvailabilityIdRoute: typeof WorkspaceAvailabilityIdRoute
  WorkspaceBookingsIdRoute: typeof WorkspaceBookingsIdRoute
  WorkspaceDistributionIdRoute: typeof WorkspaceDistributionIdRoute
  WorkspaceFacilitiesIdRoute: typeof WorkspaceFacilitiesIdRoute
  WorkspaceOpportunitiesIdRoute: typeof WorkspaceOpportunitiesIdRoute
  WorkspaceOrganizationsIdRoute: typeof WorkspaceOrganizationsIdRoute
  WorkspacePeopleIdRoute: typeof WorkspacePeopleIdRoute
  WorkspaceProductsIdRoute: typeof WorkspaceProductsIdRoute
  WorkspacePropertiesIdRoute: typeof WorkspacePropertiesIdRoute
  WorkspacePropertyGroupsIdRoute: typeof WorkspacePropertyGroupsIdRoute
  WorkspaceQuotesIdRoute: typeof WorkspaceQuotesIdRoute
  WorkspaceResourcesIdRoute: typeof WorkspaceResourcesIdRoute
  WorkspaceSuppliersIdRoute: typeof WorkspaceSuppliersIdRoute
  WorkspaceActivitiesIndexRoute: typeof WorkspaceActivitiesIndexRoute
  WorkspaceAvailabilityIndexRoute: typeof WorkspaceAvailabilityIndexRoute
  WorkspaceBookingRequirementsIndexRoute: typeof WorkspaceBookingRequirementsIndexRoute
  WorkspaceBookingsIndexRoute: typeof WorkspaceBookingsIndexRoute
  WorkspaceDistributionIndexRoute: typeof WorkspaceDistributionIndexRoute
  WorkspaceExternalRefsIndexRoute: typeof WorkspaceExternalRefsIndexRoute
  WorkspaceExtrasIndexRoute: typeof WorkspaceExtrasIndexRoute
  WorkspaceFacilitiesIndexRoute: typeof WorkspaceFacilitiesIndexRoute
  WorkspaceFinanceIndexRoute: typeof WorkspaceFinanceIndexRoute
  WorkspaceGroundIndexRoute: typeof WorkspaceGroundIndexRoute
  WorkspaceHospitalityIndexRoute: typeof WorkspaceHospitalityIndexRoute
  WorkspaceIdentityIndexRoute: typeof WorkspaceIdentityIndexRoute
  WorkspaceMarketsIndexRoute: typeof WorkspaceMarketsIndexRoute
  WorkspaceOpportunitiesIndexRoute: typeof WorkspaceOpportunitiesIndexRoute
  WorkspaceOrganizationsIndexRoute: typeof WorkspaceOrganizationsIndexRoute
  WorkspacePeopleIndexRoute: typeof WorkspacePeopleIndexRoute
  WorkspaceProductsIndexRoute: typeof WorkspaceProductsIndexRoute
  WorkspacePropertiesIndexRoute: typeof WorkspacePropertiesIndexRoute
  WorkspacePropertyGroupsIndexRoute: typeof WorkspacePropertyGroupsIndexRoute
  WorkspaceQuotesIndexRoute: typeof WorkspaceQuotesIndexRoute
  WorkspaceResourcesIndexRoute: typeof WorkspaceResourcesIndexRoute
  WorkspaceSellabilityIndexRoute: typeof WorkspaceSellabilityIndexRoute
  WorkspaceSuppliersIndexRoute: typeof WorkspaceSuppliersIndexRoute
  WorkspaceTransactionsIndexRoute: typeof WorkspaceTransactionsIndexRoute
  WorkspaceAvailabilityRulesIdRoute: typeof WorkspaceAvailabilityRulesIdRoute
  WorkspaceAvailabilityStartTimesIdRoute: typeof WorkspaceAvailabilityStartTimesIdRoute
  WorkspaceDistributionBookingLinksIdRoute: typeof WorkspaceDistributionBookingLinksIdRoute
  WorkspaceDistributionCommissionRulesIdRoute: typeof WorkspaceDistributionCommissionRulesIdRoute
  WorkspaceDistributionContractsIdRoute: typeof WorkspaceDistributionContractsIdRoute
  WorkspaceDistributionMappingsIdRoute: typeof WorkspaceDistributionMappingsIdRoute
  WorkspaceDistributionWebhookEventsIdRoute: typeof WorkspaceDistributionWebhookEventsIdRoute
  WorkspaceFinanceInvoicesIdRoute: typeof WorkspaceFinanceInvoicesIdRoute
  WorkspaceLegalContractsIdRoute: typeof WorkspaceLegalContractsIdRoute
  WorkspaceLegalPoliciesIdRoute: typeof WorkspaceLegalPoliciesIdRoute
  WorkspaceResourcesAllocationsIdRoute: typeof WorkspaceResourcesAllocationsIdRoute
  WorkspaceResourcesAssignmentsIdRoute: typeof WorkspaceResourcesAssignmentsIdRoute
  WorkspaceResourcesPoolsIdRoute: typeof WorkspaceResourcesPoolsIdRoute
  WorkspaceLegalContractsIndexRoute: typeof WorkspaceLegalContractsIndexRoute
  WorkspaceLegalNumberSeriesIndexRoute: typeof WorkspaceLegalNumberSeriesIndexRoute
  WorkspaceLegalPoliciesIndexRoute: typeof WorkspaceLegalPoliciesIndexRoute
  WorkspaceLegalTemplatesIndexRoute: typeof WorkspaceLegalTemplatesIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceAvailabilityIdRoute: WorkspaceAvailabilityIdRoute,
  WorkspaceBookingsIdRoute: WorkspaceBookingsIdRoute,
  WorkspaceDistributionIdRoute: WorkspaceDistributionIdRoute,
  WorkspaceFacilitiesIdRoute: WorkspaceFacilitiesIdRoute,
  WorkspaceOpportunitiesIdRoute: WorkspaceOpportunitiesIdRoute,
  WorkspaceOrganizationsIdRoute: WorkspaceOrganizationsIdRoute,
  WorkspacePeopleIdRoute: WorkspacePeopleIdRoute,
  WorkspaceProductsIdRoute: WorkspaceProductsIdRoute,
  WorkspacePropertiesIdRoute: WorkspacePropertiesIdRoute,
  WorkspacePropertyGroupsIdRoute: WorkspacePropertyGroupsIdRoute,
  WorkspaceQuotesIdRoute: WorkspaceQuotesIdRoute,
  WorkspaceResourcesIdRoute: WorkspaceResourcesIdRoute,
  WorkspaceSuppliersIdRoute: WorkspaceSuppliersIdRoute,
  WorkspaceActivitiesIndexRoute: WorkspaceActivitiesIndexRoute,
  WorkspaceAvailabilityIndexRoute: WorkspaceAvailabilityIndexRoute,
  WorkspaceBookingRequirementsIndexRoute:
    WorkspaceBookingRequirementsIndexRoute,
  WorkspaceBookingsIndexRoute: WorkspaceBookingsIndexRoute,
  WorkspaceDistributionIndexRoute: WorkspaceDistributionIndexRoute,
  WorkspaceExternalRefsIndexRoute: WorkspaceExternalRefsIndexRoute,
  WorkspaceExtrasIndexRoute: WorkspaceExtrasIndexRoute,
  WorkspaceFacilitiesIndexRoute: WorkspaceFacilitiesIndexRoute,
  WorkspaceFinanceIndexRoute: WorkspaceFinanceIndexRoute,
  WorkspaceGroundIndexRoute: WorkspaceGroundIndexRoute,
  WorkspaceHospitalityIndexRoute: WorkspaceHospitalityIndexRoute,
  WorkspaceIdentityIndexRoute: WorkspaceIdentityIndexRoute,
  WorkspaceMarketsIndexRoute: WorkspaceMarketsIndexRoute,
  WorkspaceOpportunitiesIndexRoute: WorkspaceOpportunitiesIndexRoute,
  WorkspaceOrganizationsIndexRoute: WorkspaceOrganizationsIndexRoute,
  WorkspacePeopleIndexRoute: WorkspacePeopleIndexRoute,
  WorkspaceProductsIndexRoute: WorkspaceProductsIndexRoute,
  WorkspacePropertiesIndexRoute: WorkspacePropertiesIndexRoute,
  WorkspacePropertyGroupsIndexRoute: WorkspacePropertyGroupsIndexRoute,
  WorkspaceQuotesIndexRoute: WorkspaceQuotesIndexRoute,
  WorkspaceResourcesIndexRoute: WorkspaceResourcesIndexRoute,
  WorkspaceSellabilityIndexRoute: WorkspaceSellabilityIndexRoute,
  WorkspaceSuppliersIndexRoute: WorkspaceSuppliersIndexRoute,
  WorkspaceTransactionsIndexRoute: WorkspaceTransactionsIndexRoute,
  WorkspaceAvailabilityRulesIdRoute: WorkspaceAvailabilityRulesIdRoute,
  WorkspaceAvailabilityStartTimesIdRoute:
    WorkspaceAvailabilityStartTimesIdRoute,
  WorkspaceDistributionBookingLinksIdRoute:
    WorkspaceDistributionBookingLinksIdRoute,
  WorkspaceDistributionCommissionRulesIdRoute:
    WorkspaceDistributionCommissionRulesIdRoute,
  WorkspaceDistributionContractsIdRoute: WorkspaceDistributionContractsIdRoute,
  WorkspaceDistributionMappingsIdRoute: WorkspaceDistributionMappingsIdRoute,
  WorkspaceDistributionWebhookEventsIdRoute:
    WorkspaceDistributionWebhookEventsIdRoute,
  WorkspaceFinanceInvoicesIdRoute: WorkspaceFinanceInvoicesIdRoute,
  WorkspaceLegalContractsIdRoute: WorkspaceLegalContractsIdRoute,
  WorkspaceLegalPoliciesIdRoute: WorkspaceLegalPoliciesIdRoute,
  WorkspaceResourcesAllocationsIdRoute: WorkspaceResourcesAllocationsIdRoute,
  WorkspaceResourcesAssignmentsIdRoute: WorkspaceResourcesAssignmentsIdRoute,
  WorkspaceResourcesPoolsIdRoute: WorkspaceResourcesPoolsIdRoute,
  WorkspaceLegalContractsIndexRoute: WorkspaceLegalContractsIndexRoute,
  WorkspaceLegalNumberSeriesIndexRoute: WorkspaceLegalNumberSeriesIndexRoute,
  WorkspaceLegalPoliciesIndexRoute: WorkspaceLegalPoliciesIndexRoute,
  WorkspaceLegalTemplatesIndexRoute: WorkspaceLegalTemplatesIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
