const localizedCountriesWithRegionsData = {
  en: [
    { name: "Afghanistan", code: "AF", region: "as", slug: "afghanistan" },
    { name: "Åland Islands", code: "AX", region: "eu", slug: "aland-islands" },
    { name: "Albania", code: "AL", region: "eu", slug: "albania" },
    { name: "Algeria", code: "DZ", region: "af", slug: "algeria" },
    { name: "American Samoa", code: "AS", region: "oc", slug: "american-samoa" },
    { name: "Andorra", code: "AD", region: "eu", slug: "andorra" },
    { name: "Angola", code: "AO", region: "af", slug: "angola" },
    { name: "Anguilla", code: "AI", region: "na", slug: "anguilla" },
    { name: "Antarctica", code: "AQ", region: "an", slug: "antarctica" },
    { name: "Antigua and Barbuda", code: "AG", region: "na", slug: "antigua-and-barbuda" },
    { name: "Argentina", code: "AR", region: "sa", slug: "argentina" },
    { name: "Armenia", code: "AM", region: "as", slug: "armenia" },
    { name: "Aruba", code: "AW", region: "na", slug: "aruba" },
    { name: "Australia", code: "AU", region: "oc", slug: "australia" },
    { name: "Austria", code: "AT", region: "eu", slug: "austria" },
    { name: "Azerbaijan", code: "AZ", region: "as", slug: "azerbaijan" },
    { name: "Bahamas", code: "BS", region: "na", slug: "bahamas" },
    { name: "Bahrain", code: "BH", region: "me", slug: "bahrain" },
    { name: "Bangladesh", code: "BD", region: "as", slug: "bangladesh" },
    { name: "Barbados", code: "BB", region: "na", slug: "barbados" },
    { name: "Belarus", code: "BY", region: "eu", slug: "belarus" },
    { name: "Belgium", code: "BE", region: "eu", slug: "belgium" },
    { name: "Belize", code: "BZ", region: "na", slug: "belize" },
    { name: "Benin", code: "BJ", region: "af", slug: "benin" },
    { name: "Bermuda", code: "BM", region: "na", slug: "bermuda" },
    { name: "Bhutan", code: "BT", region: "as", slug: "bhutan" },
    { name: "Bolivia", code: "BO", region: "sa", slug: "bolivia" },
    { name: "Bosnia and Herzegovina", code: "BA", region: "eu", slug: "bosnia-and-herzegovina" },
    { name: "Botswana", code: "BW", region: "af", slug: "botswana" },
    { name: "Bouvet Island", code: "BV", region: "an", slug: "bouvet-island" },
    { name: "Brazil", code: "BR", region: "sa", slug: "brazil" },
    {
      name: "British Indian Ocean Territory",
      code: "IO",
      region: "af",
      slug: "british-indian-ocean-territory",
    },
    { name: "Brunei Darussalam", code: "BN", region: "as", slug: "brunei-darussalam" },
    { name: "Bulgaria", code: "BG", region: "eu", slug: "bulgaria" },
    { name: "Burkina Faso", code: "BF", region: "af", slug: "burkina-faso" },
    { name: "Burundi", code: "BI", region: "af", slug: "burundi" },
    { name: "Cambodia", code: "KH", region: "as", slug: "cambodia" },
    { name: "Cameroon", code: "CM", region: "af", slug: "cameroon" },
    { name: "Canada", code: "CA", region: "na", slug: "canada" },
    { name: "Cape Verde", code: "CV", region: "af", slug: "cape-verde" },
    { name: "Cayman Islands", code: "KY", region: "na", slug: "cayman-islands" },
    {
      name: "Central African Republic",
      code: "CF",
      region: "af",
      slug: "central-african-republic",
    },
    { name: "Chad", code: "TD", region: "af", slug: "chad" },
    { name: "Chile", code: "CL", region: "sa", slug: "chile" },
    { name: "China", code: "CN", region: "as", slug: "china" },
    { name: "Christmas Island", code: "CX", region: "oc", slug: "christmas-island" },
    { name: "Cocos (Keeling) Islands", code: "CC", region: "oc", slug: "cocos-keeling-islands" },
    { name: "Colombia", code: "CO", region: "sa", slug: "colombia" },
    { name: "Comoros", code: "KM", region: "af", slug: "comoros" },
    { name: "Congo", code: "CG", region: "af", slug: "congo" },
    {
      name: "Congo, The Democratic Republic of the",
      code: "CD",
      region: "af",
      slug: "congo-the-democratic-republic-of-the",
    },
    { name: "Cook Islands", code: "CK", region: "oc", slug: "cook-islands" },
    { name: "Costa Rica", code: "CR", region: "na", slug: "costa-rica" },
    { name: "Cote D'Ivoire", code: "CI", region: "af", slug: "cote-d-ivoire" },
    { name: "Croatia", code: "HR", region: "eu", slug: "croatia" },
    { name: "Cuba", code: "CU", region: "na", slug: "cuba" },
    { name: "Cyprus", code: "CY", region: "me", slug: "cyprus" },
    { name: "Czech Republic", code: "CZ", region: "eu", slug: "czech-republic" },
    { name: "Denmark", code: "DK", region: "eu", slug: "denmark" },
    { name: "Djibouti", code: "DJ", region: "af", slug: "djibouti" },
    { name: "Dominica", code: "DM", region: "na", slug: "dominica" },
    { name: "Dominican Republic", code: "DO", region: "na", slug: "dominican-republic" },
    { name: "Ecuador", code: "EC", region: "sa", slug: "ecuador" },
    { name: "Egypt", code: "EG", region: "af", slug: "egypt" },
    { name: "El Salvador", code: "SV", region: "na", slug: "el-salvador" },
    { name: "Equatorial Guinea", code: "GQ", region: "af", slug: "equatorial-guinea" },
    { name: "Eritrea", code: "ER", region: "af", slug: "eritrea" },
    { name: "Estonia", code: "EE", region: "eu", slug: "estonia" },
    { name: "Ethiopia", code: "ET", region: "af", slug: "ethiopia" },
    {
      name: "Falkland Islands (Malvinas)",
      code: "FK",
      region: "sa",
      slug: "falkland-islands-malvinas",
    },
    { name: "Faroe Islands", code: "FO", region: "eu", slug: "faroe-islands" },
    { name: "Fiji", code: "FJ", region: "oc", slug: "fiji" },
    { name: "Finland", code: "FI", region: "eu", slug: "finland" },
    { name: "France", code: "FR", region: "eu", slug: "france" },
    { name: "French Guiana", code: "GF", region: "sa", slug: "french-guiana" },
    { name: "French Polynesia", code: "PF", region: "oc", slug: "french-polynesia" },
    {
      name: "French Southern Territories",
      code: "TF",
      region: "an",
      slug: "french-southern-territories",
    },
    { name: "Gabon", code: "GA", region: "af", slug: "gabon" },
    { name: "Gambia", code: "GM", region: "af", slug: "gambia" },
    { name: "Georgia", code: "GE", region: "as", slug: "georgia" },
    { name: "Germany", code: "DE", region: "eu", slug: "germany" },
    { name: "Ghana", code: "GH", region: "af", slug: "ghana" },
    { name: "Gibraltar", code: "GI", region: "eu", slug: "gibraltar" },
    { name: "Greece", code: "GR", region: "eu", slug: "greece" },
    { name: "Greenland", code: "GL", region: "na", slug: "greenland" },
    { name: "Grenada", code: "GD", region: "na", slug: "grenada" },
    { name: "Guadeloupe", code: "GP", region: "na", slug: "guadeloupe" },
    { name: "Guam", code: "GU", region: "oc", slug: "guam" },
    { name: "Guatemala", code: "GT", region: "na", slug: "guatemala" },
    { name: "Guernsey", code: "GG", region: "eu", slug: "guernsey" },
    { name: "Guinea", code: "GN", region: "af", slug: "guinea" },
    { name: "Guinea-Bissau", code: "GW", region: "af", slug: "guinea-bissau" },
    { name: "Guyana", code: "GY", region: "sa", slug: "guyana" },
    { name: "Haiti", code: "HT", region: "na", slug: "haiti" },
    {
      name: "Heard Island and Mcdonald Islands",
      code: "HM",
      region: "an",
      slug: "heard-island-and-mcdonald-islands",
    },
    {
      name: "Holy See (Vatican City State)",
      code: "VA",
      region: "eu",
      slug: "holy-see-vatican-city-state",
    },
    { name: "Honduras", code: "HN", region: "na", slug: "honduras" },
    { name: "Hong Kong", code: "HK", region: "as", slug: "hong-kong" },
    { name: "Hungary", code: "HU", region: "eu", slug: "hungary" },
    { name: "Iceland", code: "IS", region: "eu", slug: "iceland" },
    { name: "India", code: "IN", region: "as", slug: "india" },
    { name: "Indonesia", code: "ID", region: "as", slug: "indonesia" },
    {
      name: "Iran, Islamic Republic Of",
      code: "IR",
      region: "me",
      slug: "iran-islamic-republic-of",
    },
    { name: "Iraq", code: "IQ", region: "me", slug: "iraq" },
    { name: "Ireland", code: "IE", region: "eu", slug: "ireland" },
    { name: "Isle of Man", code: "IM", region: "eu", slug: "isle-of-man" },
    { name: "Israel", code: "IL", region: "me", slug: "israel" },
    { name: "Italy", code: "IT", region: "eu", slug: "italy" },
    { name: "Jamaica", code: "JM", region: "na", slug: "jamaica" },
    { name: "Japan", code: "JP", region: "as", slug: "japan" },
    { name: "Jersey", code: "JE", region: "eu", slug: "jersey" },
    { name: "Jordan", code: "JO", region: "me", slug: "jordan" },
    { name: "Kazakhstan", code: "KZ", region: "as", slug: "kazakhstan" },
    { name: "Kenya", code: "KE", region: "af", slug: "kenya" },
    { name: "Kiribati", code: "KI", region: "oc", slug: "kiribati" },
    {
      name: "Korea, Democratic People’s Republic of",
      code: "KP",
      region: "as",
      slug: "korea-democratic-people-s-republic-of",
    },
    { name: "Korea, Republic of", code: "KR", region: "as", slug: "korea-republic-of" },
    { name: "Kuwait", code: "KW", region: "me", slug: "kuwait" },
    { name: "Kyrgyzstan", code: "KG", region: "as", slug: "kyrgyzstan" },
    {
      name: "Lao People’s Democratic Republic",
      code: "LA",
      region: "as",
      slug: "lao-people-s-democratic-republic",
    },
    { name: "Latvia", code: "LV", region: "eu", slug: "latvia" },
    { name: "Lebanon", code: "LB", region: "me", slug: "lebanon" },
    { name: "Lesotho", code: "LS", region: "af", slug: "lesotho" },
    { name: "Liberia", code: "LR", region: "af", slug: "liberia" },
    { name: "Libyan Arab Jamahiriya", code: "LY", region: "af", slug: "libyan-arab-jamahiriya" },
    { name: "Liechtenstein", code: "LI", region: "eu", slug: "liechtenstein" },
    { name: "Lithuania", code: "LT", region: "eu", slug: "lithuania" },
    { name: "Luxembourg", code: "LU", region: "eu", slug: "luxembourg" },
    { name: "Macao", code: "MO", region: "as", slug: "macao" },
    {
      name: "Macedonia, The Former Yugoslav Republic of",
      code: "MK",
      region: "eu",
      slug: "macedonia-the-former-yugoslav-republic-of",
    },
    { name: "Madagascar", code: "MG", region: "af", slug: "madagascar" },
    { name: "Malawi", code: "MW", region: "af", slug: "malawi" },
    { name: "Malaysia", code: "MY", region: "as", slug: "malaysia" },
    { name: "Maldives", code: "MV", region: "as", slug: "maldives" },
    { name: "Mali", code: "ML", region: "af", slug: "mali" },
    { name: "Malta", code: "MT", region: "eu", slug: "malta" },
    { name: "Marshall Islands", code: "MH", region: "oc", slug: "marshall-islands" },
    { name: "Martinique", code: "MQ", region: "na", slug: "martinique" },
    { name: "Mauritania", code: "MR", region: "af", slug: "mauritania" },
    { name: "Mauritius", code: "MU", region: "af", slug: "mauritius" },
    { name: "Mayotte", code: "YT", region: "af", slug: "mayotte" },
    { name: "Mexico", code: "MX", region: "na", slug: "mexico" },
    {
      name: "Micronesia, Federated States of",
      code: "FM",
      region: "oc",
      slug: "micronesia-federated-states-of",
    },
    { name: "Moldova, Republic of", code: "MD", region: "eu", slug: "moldova-republic-of" },
    { name: "Monaco", code: "MC", region: "eu", slug: "monaco" },
    { name: "Mongolia", code: "MN", region: "as", slug: "mongolia" },
    { name: "Montserrat", code: "MS", region: "na", slug: "montserrat" },
    { name: "Morocco", code: "MA", region: "af", slug: "morocco" },
    { name: "Mozambique", code: "MZ", region: "af", slug: "mozambique" },
    { name: "Myanmar", code: "MM", region: "as", slug: "myanmar" },
    { name: "Namibia", code: "NA", region: "af", slug: "namibia" },
    { name: "Nauru", code: "NR", region: "oc", slug: "nauru" },
    { name: "Nepal", code: "NP", region: "as", slug: "nepal" },
    { name: "Netherlands", code: "NL", region: "eu", slug: "netherlands" },
    { name: "Netherlands Antilles", code: "AN", region: "na", slug: "netherlands-antilles" },
    { name: "New Caledonia", code: "NC", region: "oc", slug: "new-caledonia" },
    { name: "New Zealand", code: "NZ", region: "oc", slug: "new-zealand" },
    { name: "Nicaragua", code: "NI", region: "na", slug: "nicaragua" },
    { name: "Niger", code: "NE", region: "af", slug: "niger" },
    { name: "Nigeria", code: "NG", region: "af", slug: "nigeria" },
    { name: "Niue", code: "NU", region: "oc", slug: "niue" },
    { name: "Norfolk Island", code: "NF", region: "oc", slug: "norfolk-island" },
    {
      name: "Northern Mariana Islands",
      code: "MP",
      region: "oc",
      slug: "northern-mariana-islands",
    },
    { name: "Norway", code: "NO", region: "eu", slug: "norway" },
    { name: "Oman", code: "OM", region: "me", slug: "oman" },
    { name: "Pakistan", code: "PK", region: "as", slug: "pakistan" },
    { name: "Palau", code: "PW", region: "oc", slug: "palau" },
    {
      name: "Palestinian Territory, Occupied",
      code: "PS",
      region: "me",
      slug: "palestinian-territory-occupied",
    },
    { name: "Panama", code: "PA", region: "na", slug: "panama" },
    { name: "Papua New Guinea", code: "PG", region: "oc", slug: "papua-new-guinea" },
    { name: "Paraguay", code: "PY", region: "sa", slug: "paraguay" },
    { name: "Peru", code: "PE", region: "sa", slug: "peru" },
    { name: "Philippines", code: "PH", region: "as", slug: "philippines" },
    { name: "Pitcairn", code: "PN", region: "oc", slug: "pitcairn" },
    { name: "Poland", code: "PL", region: "eu", slug: "poland" },
    { name: "Portugal", code: "PT", region: "eu", slug: "portugal" },
    { name: "Puerto Rico", code: "PR", region: "na", slug: "puerto-rico" },
    { name: "Qatar", code: "QA", region: "me", slug: "qatar" },
    { name: "Reunion", code: "RE", region: "af", slug: "reunion" },
    { name: "Romania", code: "RO", region: "eu", slug: "romania" },
    { name: "Russian Federation", code: "RU", region: "eu", slug: "russian-federation" },
    { name: "RWANDA", code: "RW", region: "af", slug: "rwanda" },
    { name: "Saint Helena", code: "SH", region: "af", slug: "saint-helena" },
    { name: "Saint Kitts and Nevis", code: "KN", region: "na", slug: "saint-kitts-and-nevis" },
    { name: "Saint Lucia", code: "LC", region: "na", slug: "saint-lucia" },
    {
      name: "Saint Pierre and Miquelon",
      code: "PM",
      region: "na",
      slug: "saint-pierre-and-miquelon",
    },
    {
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      region: "na",
      slug: "saint-vincent-and-the-grenadines",
    },
    { name: "Samoa", code: "WS", region: "oc", slug: "samoa" },
    { name: "San Marino", code: "SM", region: "eu", slug: "san-marino" },
    { name: "Sao Tome and Principe", code: "ST", region: "af", slug: "sao-tome-and-principe" },
    { name: "Saudi Arabia", code: "SA", region: "me", slug: "saudi-arabia" },
    { name: "Senegal", code: "SN", region: "af", slug: "senegal" },
    { name: "Serbia and Montenegro", code: "CS", region: "eu", slug: "serbia-and-montenegro" },
    { name: "Seychelles", code: "SC", region: "af", slug: "seychelles" },
    { name: "Sierra Leone", code: "SL", region: "af", slug: "sierra-leone" },
    { name: "Singapore", code: "SG", region: "as", slug: "singapore" },
    { name: "Slovakia", code: "SK", region: "eu", slug: "slovakia" },
    { name: "Slovenia", code: "SI", region: "eu", slug: "slovenia" },
    { name: "Solomon Islands", code: "SB", region: "oc", slug: "solomon-islands" },
    { name: "Somalia", code: "SO", region: "af", slug: "somalia" },
    { name: "South Africa", code: "ZA", region: "af", slug: "south-africa" },
    {
      name: "South Georgia and the South Sandwich Islands",
      code: "GS",
      region: "sa",
      slug: "south-georgia-and-the-south-sandwich-islands",
    },
    { name: "Spain", code: "ES", region: "eu", slug: "spain" },
    { name: "Sri Lanka", code: "LK", region: "as", slug: "sri-lanka" },
    { name: "Sudan", code: "SD", region: "af", slug: "sudan" },
    { name: "Suriname", code: "SR", region: "sa", slug: "suriname" },
    { name: "Svalbard and Jan Mayen", code: "SJ", region: "eu", slug: "svalbard-and-jan-mayen" },
    { name: "Swaziland", code: "SZ", region: "af", slug: "swaziland" },
    { name: "Sweden", code: "SE", region: "eu", slug: "sweden" },
    { name: "Switzerland", code: "CH", region: "eu", slug: "switzerland" },
    { name: "Syrian Arab Republic", code: "SY", region: "me", slug: "syrian-arab-republic" },
    {
      name: "Taiwan, Province of China",
      code: "TW",
      region: "as",
      slug: "taiwan-province-of-china",
    },
    { name: "Tajikistan", code: "TJ", region: "as", slug: "tajikistan" },
    {
      name: "Tanzania, United Republic of",
      code: "TZ",
      region: "af",
      slug: "tanzania-united-republic-of",
    },
    { name: "Thailand", code: "TH", region: "as", slug: "thailand" },
    { name: "Timor-Leste", code: "TL", region: "as", slug: "timor-leste" },
    { name: "Togo", code: "TG", region: "af", slug: "togo" },
    { name: "Tokelau", code: "TK", region: "oc", slug: "tokelau" },
    { name: "Tonga", code: "TO", region: "oc", slug: "tonga" },
    { name: "Trinidad and Tobago", code: "TT", region: "na", slug: "trinidad-and-tobago" },
    { name: "Tunisia", code: "TN", region: "af", slug: "tunisia" },
    { name: "Turkey", code: "TR", region: "me", slug: "turkey" },
    { name: "Turkmenistan", code: "TM", region: "as", slug: "turkmenistan" },
    {
      name: "Turks and Caicos Islands",
      code: "TC",
      region: "na",
      slug: "turks-and-caicos-islands",
    },
    { name: "Tuvalu", code: "TV", region: "oc", slug: "tuvalu" },
    { name: "Uganda", code: "UG", region: "af", slug: "uganda" },
    { name: "Ukraine", code: "UA", region: "eu", slug: "ukraine" },
    { name: "United Arab Emirates", code: "AE", region: "me", slug: "united-arab-emirates" },
    { name: "United Kingdom", code: "GB", region: "eu", slug: "united-kingdom" },
    { name: "United States", code: "US", region: "na", slug: "united-states" },
    {
      name: "United States Minor Outlying Islands",
      code: "UM",
      region: "oc",
      slug: "united-states-minor-outlying-islands",
    },
    { name: "Uruguay", code: "UY", region: "sa", slug: "uruguay" },
    { name: "Uzbekistan", code: "UZ", region: "as", slug: "uzbekistan" },
    { name: "Vanuatu", code: "VU", region: "oc", slug: "vanuatu" },
    { name: "Venezuela", code: "VE", region: "sa", slug: "venezuela" },
    { name: "Viet Nam", code: "VN", region: "as", slug: "viet-nam" },
    { name: "Virgin Islands, British", code: "VG", region: "na", slug: "virgin-islands-british" },
    { name: "Virgin Islands, U.S.", code: "VI", region: "na", slug: "virgin-islands-u-s" },
    { name: "Wallis and Futuna", code: "WF", region: "oc", slug: "wallis-and-futuna" },
    { name: "Western Sahara", code: "EH", region: "af", slug: "western-sahara" },
    { name: "Yemen", code: "YE", region: "me", slug: "yemen" },
    { name: "Zambia", code: "ZM", region: "af", slug: "zambia" },
    { name: "Zimbabwe", code: "ZW", region: "af", slug: "zimbabwe" },
  ],
  ro: [
    { name: "Afghanistan", code: "AF", region: "as", slug: "afghanistan" },
    { name: "Insulele Åland", code: "AX", region: "eu", slug: "insulele-aland" },
    { name: "Albania", code: "AL", region: "eu", slug: "albania" },
    { name: "Algeria", code: "DZ", region: "af", slug: "algeria" },
    { name: "Samoa Americană", code: "AS", region: "oc", slug: "samoa-americana" },
    { name: "Andorra", code: "AD", region: "eu", slug: "andorra" },
    { name: "Angola", code: "AO", region: "af", slug: "angola" },
    { name: "Anguilla", code: "AI", region: "na", slug: "anguilla" },
    { name: "Antarctica", code: "AQ", region: "an", slug: "antarctica" },
    { name: "Antigua și Barbuda", code: "AG", region: "na", slug: "antigua-si-barbuda" },
    { name: "Argentina", code: "AR", region: "sa", slug: "argentina" },
    { name: "Armenia", code: "AM", region: "as", slug: "armenia" },
    { name: "Aruba", code: "AW", region: "na", slug: "aruba" },
    { name: "Australia", code: "AU", region: "oc", slug: "australia" },
    { name: "Austria", code: "AT", region: "eu", slug: "austria" },
    { name: "Azerbaidjan", code: "AZ", region: "as", slug: "azerbaidjan" },
    { name: "Bahamas", code: "BS", region: "na", slug: "bahamas" },
    { name: "Bahrain", code: "BH", region: "me", slug: "bahrain" },
    { name: "Bangladesh", code: "BD", region: "as", slug: "bangladesh" },
    { name: "Barbados", code: "BB", region: "na", slug: "barbados" },
    { name: "Belarus", code: "BY", region: "eu", slug: "belarus" },
    { name: "Belgia", code: "BE", region: "eu", slug: "belgia" },
    { name: "Belize", code: "BZ", region: "na", slug: "belize" },
    { name: "Benin", code: "BJ", region: "af", slug: "benin" },
    { name: "Bermuda", code: "BM", region: "na", slug: "bermuda" },
    { name: "Bhutan", code: "BT", region: "as", slug: "bhutan" },
    { name: "Bolivia", code: "BO", region: "sa", slug: "bolivia" },
    { name: "Bosnia și Herțegovina", code: "BA", region: "eu", slug: "bosnia-si-hertegovina" },
    { name: "Botswana", code: "BW", region: "af", slug: "botswana" },
    { name: "Insula Bouvet", code: "BV", region: "an", slug: "insula-bouvet" },
    { name: "Brazilia", code: "BR", region: "sa", slug: "brazilia" },
    {
      name: "Teritoriul Britanic din Oceanul Indian",
      code: "IO",
      region: "af",
      slug: "teritoriul-britanic-din-oceanul-indian",
    },
    { name: "Brunei Darussalam", code: "BN", region: "as", slug: "brunei-darussalam" },
    { name: "Bulgaria", code: "BG", region: "eu", slug: "bulgaria" },
    { name: "Burkina Faso", code: "BF", region: "af", slug: "burkina-faso" },
    { name: "Burundi", code: "BI", region: "af", slug: "burundi" },
    { name: "Cambodgia", code: "KH", region: "as", slug: "cambodgia" },
    { name: "Camerun", code: "CM", region: "af", slug: "camerun" },
    { name: "Canada", code: "CA", region: "na", slug: "canada" },
    { name: "Capul Verde", code: "CV", region: "af", slug: "capul-verde" },
    { name: "Insulele Cayman", code: "KY", region: "na", slug: "insulele-cayman" },
    { name: "Republica Centrafricană", code: "CF", region: "af", slug: "republica-centrafricana" },
    { name: "Ciad", code: "TD", region: "af", slug: "ciad" },
    { name: "Chile", code: "CL", region: "sa", slug: "chile" },
    { name: "China", code: "CN", region: "as", slug: "china" },
    { name: "Insula Christmas", code: "CX", region: "oc", slug: "insula-christmas" },
    { name: "Insulele Cocos (Keeling)", code: "CC", region: "oc", slug: "insulele-cocos-keeling" },
    { name: "Columbia", code: "CO", region: "sa", slug: "columbia" },
    { name: "Comore", code: "KM", region: "af", slug: "comore" },
    { name: "Congo", code: "CG", region: "af", slug: "congo" },
    {
      name: "Congo, Republica Democrată",
      code: "CD",
      region: "af",
      slug: "congo-republica-democrata",
    },
    { name: "Insulele Cook", code: "CK", region: "oc", slug: "insulele-cook" },
    { name: "Costa Rica", code: "CR", region: "na", slug: "costa-rica" },
    { name: "Coasta de Fildeș", code: "CI", region: "af", slug: "coasta-de-fildes" },
    { name: "Croația", code: "HR", region: "eu", slug: "croatia" },
    { name: "Cuba", code: "CU", region: "na", slug: "cuba" },
    { name: "Cipru", code: "CY", region: "me", slug: "cipru" },
    { name: "Republica Cehă", code: "CZ", region: "eu", slug: "republica-ceha" },
    { name: "Danemarca", code: "DK", region: "eu", slug: "danemarca" },
    { name: "Djibouti", code: "DJ", region: "af", slug: "djibouti" },
    { name: "Dominica", code: "DM", region: "na", slug: "dominica" },
    { name: "Republica Dominicană", code: "DO", region: "na", slug: "republica-dominicana" },
    { name: "Ecuador", code: "EC", region: "sa", slug: "ecuador" },
    { name: "Egipt", code: "EG", region: "af", slug: "egipt" },
    { name: "El Salvador", code: "SV", region: "na", slug: "el-salvador" },
    { name: "Guineea Ecuatorială", code: "GQ", region: "af", slug: "guineea-ecuatoriala" },
    { name: "Eritreea", code: "ER", region: "af", slug: "eritreea" },
    { name: "Estonia", code: "EE", region: "eu", slug: "estonia" },
    { name: "Etiopia", code: "ET", region: "af", slug: "etiopia" },
    {
      name: "Insulele Falkland (Malvine)",
      code: "FK",
      region: "sa",
      slug: "insulele-falkland-malvine",
    },
    { name: "Insulele Feroe", code: "FO", region: "eu", slug: "insulele-feroe" },
    { name: "Fiji", code: "FJ", region: "oc", slug: "fiji" },
    { name: "Finlanda", code: "FI", region: "eu", slug: "finlanda" },
    { name: "Franța", code: "FR", region: "eu", slug: "franta" },
    { name: "Guyana Franceză", code: "GF", region: "sa", slug: "guyana-franceza" },
    { name: "Polinezia Franceză", code: "PF", region: "oc", slug: "polinezia-franceza" },
    {
      name: "Teritoriile Australe și Antarctice Franceze",
      code: "TF",
      region: "an",
      slug: "teritoriile-australe-si-antarctice-franceze",
    },
    { name: "Gabon", code: "GA", region: "af", slug: "gabon" },
    { name: "Gambia", code: "GM", region: "af", slug: "gambia" },
    { name: "Georgia", code: "GE", region: "as", slug: "georgia" },
    { name: "Germania", code: "DE", region: "eu", slug: "germania" },
    { name: "Ghana", code: "GH", region: "af", slug: "ghana" },
    { name: "Gibraltar", code: "GI", region: "eu", slug: "gibraltar" },
    { name: "Grecia", code: "GR", region: "eu", slug: "grecia" },
    { name: "Groenlanda", code: "GL", region: "na", slug: "groenlanda" },
    { name: "Grenada", code: "GD", region: "na", slug: "grenada" },
    { name: "Guadeloupe", code: "GP", region: "na", slug: "guadeloupe" },
    { name: "Guam", code: "GU", region: "oc", slug: "guam" },
    { name: "Guatemala", code: "GT", region: "na", slug: "guatemala" },
    { name: "Guernsey", code: "GG", region: "eu", slug: "guernsey" },
    { name: "Guineea", code: "GN", region: "af", slug: "guineea" },
    { name: "Guineea-Bissau", code: "GW", region: "af", slug: "guineea-bissau" },
    { name: "Guyana", code: "GY", region: "sa", slug: "guyana" },
    { name: "Haiti", code: "HT", region: "na", slug: "haiti" },
    {
      name: "Insula Heard și Insulele McDonald",
      code: "HM",
      region: "an",
      slug: "insula-heard-si-insulele-mcdonald",
    },
    {
      name: "Sfântul Scaun (Statul Vatican)",
      code: "VA",
      region: "eu",
      slug: "sfantul-scaun-statul-vatican",
    },
    { name: "Honduras", code: "HN", region: "na", slug: "honduras" },
    { name: "Hong Kong", code: "HK", region: "as", slug: "hong-kong" },
    { name: "Ungaria", code: "HU", region: "eu", slug: "ungaria" },
    { name: "Islanda", code: "IS", region: "eu", slug: "islanda" },
    { name: "India", code: "IN", region: "as", slug: "india" },
    { name: "Indonezia", code: "ID", region: "as", slug: "indonezia" },
    { name: "Iran", code: "IR", region: "me", slug: "iran" },
    { name: "Irak", code: "IQ", region: "me", slug: "irak" },
    { name: "Irlanda", code: "IE", region: "eu", slug: "irlanda" },
    { name: "Insula Man", code: "IM", region: "eu", slug: "insula-man" },
    { name: "Israel", code: "IL", region: "me", slug: "israel" },
    { name: "Italia", code: "IT", region: "eu", slug: "italia" },
    { name: "Jamaica", code: "JM", region: "na", slug: "jamaica" },
    { name: "Japonia", code: "JP", region: "as", slug: "japonia" },
    { name: "Jersey", code: "JE", region: "eu", slug: "jersey" },
    { name: "Iordania", code: "JO", region: "me", slug: "iordania" },
    { name: "Kazahstan", code: "KZ", region: "as", slug: "kazahstan" },
    { name: "Kenya", code: "KE", region: "af", slug: "kenya" },
    { name: "Kiribati", code: "KI", region: "oc", slug: "kiribati" },
    { name: "Coreea de Nord", code: "KP", region: "as", slug: "coreea-de-nord" },
    { name: "Coreea de Sud", code: "KR", region: "as", slug: "coreea-de-sud" },
    { name: "Kuweit", code: "KW", region: "me", slug: "kuweit" },
    { name: "Kârgâzstan", code: "KG", region: "as", slug: "kargazstan" },
    { name: "Laos", code: "LA", region: "as", slug: "laos" },
    { name: "Letonia", code: "LV", region: "eu", slug: "letonia" },
    { name: "Liban", code: "LB", region: "me", slug: "liban" },
    { name: "Lesotho", code: "LS", region: "af", slug: "lesotho" },
    { name: "Liberia", code: "LR", region: "af", slug: "liberia" },
    { name: "Libia", code: "LY", region: "af", slug: "libia" },
    { name: "Liechtenstein", code: "LI", region: "eu", slug: "liechtenstein" },
    { name: "Lituania", code: "LT", region: "eu", slug: "lituania" },
    { name: "Luxemburg", code: "LU", region: "eu", slug: "luxemburg" },
    { name: "Macao", code: "MO", region: "as", slug: "macao" },
    { name: "Macedonia de Nord", code: "MK", region: "eu", slug: "macedonia-de-nord" },
    { name: "Madagascar", code: "MG", region: "af", slug: "madagascar" },
    { name: "Malawi", code: "MW", region: "af", slug: "malawi" },
    { name: "Malaezia", code: "MY", region: "as", slug: "malaezia" },
    { name: "Maldive", code: "MV", region: "as", slug: "maldive" },
    { name: "Mali", code: "ML", region: "af", slug: "mali" },
    { name: "Malta", code: "MT", region: "eu", slug: "malta" },
    { name: "Insulele Marshall", code: "MH", region: "oc", slug: "insulele-marshall" },
    { name: "Martinica", code: "MQ", region: "na", slug: "martinica" },
    { name: "Mauritania", code: "MR", region: "af", slug: "mauritania" },
    { name: "Mauritius", code: "MU", region: "af", slug: "mauritius" },
    { name: "Mayotte", code: "YT", region: "af", slug: "mayotte" },
    { name: "Mexic", code: "MX", region: "na", slug: "mexic" },
    { name: "Micronezia", code: "FM", region: "oc", slug: "micronezia" },
    { name: "Republica Moldova", code: "MD", region: "eu", slug: "republica-moldova" },
    { name: "Monaco", code: "MC", region: "eu", slug: "monaco" },
    { name: "Mongolia", code: "MN", region: "as", slug: "mongolia" },
    { name: "Montserrat", code: "MS", region: "na", slug: "montserrat" },
    { name: "Maroc", code: "MA", region: "af", slug: "maroc" },
    { name: "Mozambic", code: "MZ", region: "af", slug: "mozambic" },
    { name: "Myanmar", code: "MM", region: "as", slug: "myanmar" },
    { name: "Namibia", code: "NA", region: "af", slug: "namibia" },
    { name: "Nauru", code: "NR", region: "oc", slug: "nauru" },
    { name: "Nepal", code: "NP", region: "as", slug: "nepal" },
    { name: "Țările de Jos", code: "NL", region: "eu", slug: "tarile-de-jos" },
    { name: "Antilele Olandeze", code: "AN", region: "na", slug: "antilele-olandeze" },
    { name: "Noua Caledonie", code: "NC", region: "oc", slug: "noua-caledonie" },
    { name: "Noua Zeelandă", code: "NZ", region: "oc", slug: "noua-zeelanda" },
    { name: "Nicaragua", code: "NI", region: "na", slug: "nicaragua" },
    { name: "Niger", code: "NE", region: "af", slug: "niger" },
    { name: "Nigeria", code: "NG", region: "af", slug: "nigeria" },
    { name: "Niue", code: "NU", region: "oc", slug: "niue" },
    { name: "Insula Norfolk", code: "NF", region: "oc", slug: "insula-norfolk" },
    {
      name: "Insulele Marianei de Nord",
      code: "MP",
      region: "oc",
      slug: "insulele-marianei-de-nord",
    },
    { name: "Norvegia", code: "NO", region: "eu", slug: "norvegia" },
    { name: "Oman", code: "OM", region: "me", slug: "oman" },
    { name: "Pakistan", code: "PK", region: "as", slug: "pakistan" },
    { name: "Palau", code: "PW", region: "oc", slug: "palau" },
    {
      name: "Teritoriul Palestinian Ocupat",
      code: "PS",
      region: "me",
      slug: "teritoriul-palestinian-ocupat",
    },
    { name: "Panama", code: "PA", region: "na", slug: "panama" },
    { name: "Papua Noua Guinee", code: "PG", region: "oc", slug: "papua-noua-guinee" },
    { name: "Paraguay", code: "PY", region: "sa", slug: "paraguay" },
    { name: "Peru", code: "PE", region: "sa", slug: "peru" },
    { name: "Filipine", code: "PH", region: "as", slug: "filipine" },
    { name: "Pitcairn", code: "PN", region: "oc", slug: "pitcairn" },
    { name: "Polonia", code: "PL", region: "eu", slug: "polonia" },
    { name: "Portugalia", code: "PT", region: "eu", slug: "portugalia" },
    { name: "Puerto Rico", code: "PR", region: "na", slug: "puerto-rico" },
    { name: "Qatar", code: "QA", region: "me", slug: "qatar" },
    { name: "Réunion", code: "RE", region: "af", slug: "reunion" },
    { name: "Romania", code: "RO", region: "eu", slug: "romania" },
    { name: "Federația Rusă", code: "RU", region: "eu", slug: "federatia-rusa" },
    { name: "Rwanda", code: "RW", region: "af", slug: "rwanda" },
    { name: "Sfânta Elena", code: "SH", region: "af", slug: "sfanta-elena" },
    { name: "Saint Kitts și Nevis", code: "KN", region: "na", slug: "saint-kitts-si-nevis" },
    { name: "Saint Lucia", code: "LC", region: "na", slug: "saint-lucia" },
    {
      name: "Saint Pierre și Miquelon",
      code: "PM",
      region: "na",
      slug: "saint-pierre-si-miquelon",
    },
    {
      name: "Saint Vincent și Grenadine",
      code: "VC",
      region: "na",
      slug: "saint-vincent-si-grenadine",
    },
    { name: "Samoa", code: "WS", region: "oc", slug: "samoa" },
    { name: "San Marino", code: "SM", region: "eu", slug: "san-marino" },
    { name: "Sao Tome și Principe", code: "ST", region: "af", slug: "sao-tome-si-principe" },
    { name: "Arabia Saudită", code: "SA", region: "me", slug: "arabia-saudita" },
    { name: "Senegal", code: "SN", region: "af", slug: "senegal" },
    { name: "Serbia și Muntenegru", code: "CS", region: "eu", slug: "serbia-si-muntenegru" },
    { name: "Seychelles", code: "SC", region: "af", slug: "seychelles" },
    { name: "Sierra Leone", code: "SL", region: "af", slug: "sierra-leone" },
    { name: "Singapore", code: "SG", region: "as", slug: "singapore" },
    { name: "Slovacia", code: "SK", region: "eu", slug: "slovacia" },
    { name: "Slovenia", code: "SI", region: "eu", slug: "slovenia" },
    { name: "Insulele Solomon", code: "SB", region: "oc", slug: "insulele-solomon" },
    { name: "Somalia", code: "SO", region: "af", slug: "somalia" },
    { name: "Africa de Sud", code: "ZA", region: "af", slug: "africa-de-sud" },
    {
      name: "Georgia de Sud și Insulele Sandwich de Sud",
      code: "GS",
      region: "sa",
      slug: "georgia-de-sud-si-insulele-sandwich-de-sud",
    },
    { name: "Spania", code: "ES", region: "eu", slug: "spania" },
    { name: "Sri Lanka", code: "LK", region: "as", slug: "sri-lanka" },
    { name: "Sudan", code: "SD", region: "af", slug: "sudan" },
    { name: "Surinam", code: "SR", region: "sa", slug: "surinam" },
    { name: "Svalbard și Jan Mayen", code: "SJ", region: "eu", slug: "svalbard-si-jan-mayen" },
    { name: "Swaziland (Eswatini)", code: "SZ", region: "af", slug: "swaziland-eswatini" },
    { name: "Suedia", code: "SE", region: "eu", slug: "suedia" },
    { name: "Elveția", code: "CH", region: "eu", slug: "elvetia" },
    { name: "Siria", code: "SY", region: "me", slug: "siria" },
    { name: "Taiwan", code: "TW", region: "as", slug: "taiwan" },
    { name: "Tadjikistan", code: "TJ", region: "as", slug: "tadjikistan" },
    { name: "Tanzania", code: "TZ", region: "af", slug: "tanzania" },
    { name: "Thailanda", code: "TH", region: "as", slug: "thailanda" },
    { name: "Timorul de Est", code: "TL", region: "as", slug: "timorul-de-est" },
    { name: "Togo", code: "TG", region: "af", slug: "togo" },
    { name: "Tokelau", code: "TK", region: "oc", slug: "tokelau" },
    { name: "Tonga", code: "TO", region: "oc", slug: "tonga" },
    { name: "Trinidad și Tobago", code: "TT", region: "na", slug: "trinidad-si-tobago" },
    { name: "Tunisia", code: "TN", region: "af", slug: "tunisia" },
    { name: "Turcia", code: "TR", region: "me", slug: "turcia" },
    { name: "Turkmenistan", code: "TM", region: "as", slug: "turkmenistan" },
    {
      name: "Insulele Turks și Caicos",
      code: "TC",
      region: "na",
      slug: "insulele-turks-si-caicos",
    },
    { name: "Tuvalu", code: "TV", region: "oc", slug: "tuvalu" },
    { name: "Uganda", code: "UG", region: "af", slug: "uganda" },
    { name: "Ucraina", code: "UA", region: "eu", slug: "ucraina" },
    { name: "Emiratele Arabe Unite", code: "AE", region: "me", slug: "emiratele-arabe-unite" },
    { name: "Regatul Unit", code: "GB", region: "eu", slug: "regatul-unit" },
    { name: "Statele Unite", code: "US", region: "na", slug: "statele-unite" },
    {
      name: "Insulele Minore Îndepărtate ale Statelor Unite",
      code: "UM",
      region: "oc",
      slug: "insulele-minore-indepartate-ale-statelor-unite",
    },
    { name: "Uruguay", code: "UY", region: "sa", slug: "uruguay" },
    { name: "Uzbekistan", code: "UZ", region: "as", slug: "uzbekistan" },
    { name: "Vanuatu", code: "VU", region: "oc", slug: "vanuatu" },
    { name: "Venezuela", code: "VE", region: "sa", slug: "venezuela" },
    { name: "Vietnam", code: "VN", region: "as", slug: "vietnam" },
    {
      name: "Insulele Virgine Britanice",
      code: "VG",
      region: "na",
      slug: "insulele-virgine-britanice",
    },
    {
      name: "Insulele Virgine Americane",
      code: "VI",
      region: "na",
      slug: "insulele-virgine-americane",
    },
    { name: "Wallis și Futuna", code: "WF", region: "oc", slug: "wallis-si-futuna" },
    { name: "Sahara Occidentală", code: "EH", region: "af", slug: "sahara-occidentala" },
    { name: "Yemen", code: "YE", region: "me", slug: "yemen" },
    { name: "Zambia", code: "ZM", region: "af", slug: "zambia" },
    { name: "Zimbabwe", code: "ZW", region: "af", slug: "zimbabwe" },
  ],
}

export const localizedCountriesWithRegions = localizedCountriesWithRegionsData
