export const localizedRegions = {
  en: [
    { name: "Africa", code: "af", slug: "africa" },
    { name: "Antarctica", code: "an", slug: "antarctica" },
    { name: "Asia", code: "as", slug: "asia" },
    { name: "Europe", code: "eu", slug: "europe" },
    { name: "North America", code: "na", slug: "north-america" },
    { name: "Oceania", code: "oc", slug: "oceania" },
    { name: "South America", code: "sa", slug: "south-america" },
    { name: "Middle East", code: "me", slug: "middle-east" },
  ],
  ro: [
    { name: "Africa", code: "af", slug: "africa" },
    { name: "Antarctica", code: "an", slug: "antarctica" },
    { name: "Asia", code: "as", slug: "asia" },
    { name: "Europa", code: "eu", slug: "europa" },
    { name: "America de Nord", code: "na", slug: "america-de-nord" },
    { name: "Oceania", code: "oc", slug: "oceania" },
    { name: "America de Sud", code: "sa", slug: "america-de-sud" },
    { name: "Orientul Mijlociu", code: "me", slug: "orientul-mijlociu" },
  ],
  fr: [
    { name: "Afrique", code: "af", slug: "afrique" },
    { name: "Antarctique", code: "an", slug: "antarctique" },
    { name: "Asie", code: "as", slug: "asie" },
    { name: "Europe", code: "eu", slug: "europe" },
    { name: "Amérique du Nord", code: "na", slug: "amerique-du-nord" },
    { name: "Océanie", code: "oc", slug: "oceanie" },
    { name: "Amérique du Sud", code: "sa", slug: "amerique-du-sud" },
    { name: "Moyen-Orient", code: "me", slug: "moyen-orient" },
  ],
  de: [
    { name: "Afrika", code: "af", slug: "afrika" },
    { name: "Antarktis", code: "an", slug: "antarktis" },
    { name: "Asien", code: "as", slug: "asien" },
    { name: "Europa", code: "eu", slug: "europa" },
    { name: "Nordamerika", code: "na", slug: "nordamerika" },
    { name: "Ozeanien", code: "oc", slug: "ozeanien" },
    { name: "Südamerika", code: "sa", slug: "sudamerika" },
    { name: "Naher Osten", code: "me", slug: "naher-osten" },
  ],
  es: [
    { name: "África", code: "af", slug: "africa" },
    { name: "Antártida", code: "an", slug: "antartida" },
    { name: "Asia", code: "as", slug: "asia" },
    { name: "Europa", code: "eu", slug: "europa" },
    { name: "América del Norte", code: "na", slug: "america-del-norte" },
    { name: "Oceanía", code: "oc", slug: "oceania" },
    { name: "América del Sur", code: "sa", slug: "america-del-sur" },
    { name: "Oriente Medio", code: "me", slug: "oriente-medio" },
  ],
  it: [
    { name: "Africa", code: "af", slug: "africa" },
    { name: "Antartide", code: "an", slug: "antartide" },
    { name: "Asia", code: "as", slug: "asia" },
    { name: "Europa", code: "eu", slug: "europa" },
    { name: "America del Nord", code: "na", slug: "america-del-nord" },
    { name: "Oceania", code: "oc", slug: "oceania" },
    { name: "America del Sud", code: "sa", slug: "america-del-sud" },
    { name: "Medio Oriente", code: "me", slug: "medio-oriente" },
  ],
}
