/**
 * All entity prefixes for the Voyant platform.
 * Prefixes are 2-4 characters, lowercase alphanumeric.
 */
export const PREFIXES = {
  // --- IAM ---
  user_profiles: "usrp",
  connection_secrets: "secr",

  // --- INFRA ---
  webhook_subscriptions: "hksub",
  webhook_deliveries: "whde",
  domains: "dom",
  email_domain_records: "emdr",

  // --- VOYANT MODULES ---
  communication_log: "clog",
  notification_templates: "ntpl",
  notification_deliveries: "ntdl",
  notification_reminder_rules: "ntrl",
  notification_reminder_runs: "ntrn",
  person_notes: "pnot",
  organization_notes: "onot",
  segments: "cseg",
  segment_members: "csgm",
  suppliers: "supp",
  supplier_services: "ssvc",
  supplier_rates: "srat",
  supplier_notes: "snot",
  supplier_availability: "sava",
  supplier_contracts: "scon",
  products: "prod",
  product_options: "popt",
  option_units: "ount",
  product_activation_settings: "pras",
  product_ticket_settings: "prts",
  product_visibility_settings: "prvs",
  product_capabilities: "prcp",
  product_delivery_formats: "prdf",
  product_translations: "prtr",
  product_option_translations: "potr",
  option_unit_translations: "outr",
  product_days: "pday",
  product_day_services: "pdse",
  product_versions: "pver",
  product_notes: "prnt",
  bookings: "book",
  booking_participants: "bkpt",
  booking_items: "bkit",
  booking_allocations: "bkac",
  booking_fulfillments: "bkfl",
  booking_redemption_events: "bkrd",
  booking_item_participants: "bkip",
  booking_passengers: "bkps",
  booking_supplier_statuses: "bkss",
  booking_activity_log: "bkal",
  booking_pii_access_log: "bkpl",
  booking_notes: "bnot",
  booking_documents: "bdoc",
  booking_session_states: "bkst",
  availability_rules: "avrl",
  availability_start_times: "avst",
  availability_slots: "avsl",
  availability_closeouts: "avcl",
  availability_pickup_points: "avpp",
  availability_slot_pickups: "avsp",
  product_meeting_configs: "pmcf",
  pickup_groups: "pkgr",
  pickup_locations: "pklo",
  location_pickup_times: "lpkt",
  custom_pickup_areas: "cpka",
  organizations: "orgn",
  people: "prsn",
  pipelines: "pipe",
  stages: "stge",
  opportunities: "oppt",
  opportunity_participants: "oppp",
  opportunity_products: "oppr",
  quotes: "quot",
  quote_lines: "qtln",
  activities: "actv",
  activity_links: "actl",
  activity_participants: "actp",
  custom_field_definitions: "cfdf",
  custom_field_values: "cfvl",
  invoices: "inv",
  payment_instruments: "pmin",
  payment_sessions: "pmss",
  payment_authorizations: "pmaz",
  payment_captures: "pmcp",
  booking_payment_schedules: "bkpy",
  booking_guarantees: "bkgu",
  booking_item_tax_lines: "bitx",
  booking_item_commissions: "bcom",
  invoice_line_items: "inli",
  payments: "pay",
  credit_notes: "crnt",
  credit_note_line_items: "cnli",
  supplier_payments: "spay",
  finance_notes: "fnot",
  resources: "resc",
  resource_pools: "rspl",
  resource_pool_members: "rspm",
  resource_requirements: "rsrq",
  resource_slot_assignments: "rssa",
  resource_closeouts: "rscl",
  ground_operators: "gopr",
  ground_vehicles: "gveh",
  ground_drivers: "gdrv",
  ground_transfer_preferences: "gtpr",
  ground_dispatches: "gdsp",
  ground_execution_events: "gexe",
  ground_dispatch_assignments: "gdas",
  ground_dispatch_legs: "gdlg",
  ground_dispatch_passengers: "gdps",
  ground_driver_shifts: "gdsh",
  ground_service_incidents: "gsin",
  ground_dispatch_checkpoints: "gdcp",
  channels: "chan",
  channel_contracts: "chco",
  channel_commission_rules: "chcr",
  channel_product_mappings: "chpm",
  channel_booking_links: "chbl",
  channel_webhook_events: "chwe",
  channel_inventory_allotments: "chia",
  channel_inventory_allotment_targets: "chat",
  channel_inventory_release_rules: "chir",
  channel_settlement_runs: "chsr",
  channel_settlement_items: "chsi",
  channel_reconciliation_runs: "chrr",
  channel_reconciliation_items: "chri",
  channel_inventory_release_executions: "chrx",
  channel_settlement_policies: "chsp",
  channel_reconciliation_policies: "chrp",
  channel_release_schedules: "chrs",
  channel_remittance_exceptions: "chre",
  channel_settlement_approvals: "chap",
  facilities: "faci",
  facility_contacts: "fcon",
  facility_features: "ffea",
  facility_operation_schedules: "fops",
  properties: "prop",
  property_groups: "pgrp",
  property_group_members: "pgpm",
  room_types: "hrmt",
  room_type_bed_configs: "hrbc",
  room_units: "hrun",
  meal_plans: "hmlp",
  rate_plans: "hrpl",
  rate_plan_room_types: "hrrt",
  stay_rules: "hstr",
  room_inventory: "hriv",
  rate_plan_inventory_overrides: "hrio",
  stay_booking_items: "hsbi",
  stay_daily_rates: "hsdr",
  room_type_rates: "hrtr",
  room_blocks: "hrbl",
  room_unit_status_events: "hrse",
  maintenance_blocks: "hmbl",
  housekeeping_tasks: "hhkt",
  stay_operations: "hsop",
  stay_checkpoints: "hscp",
  stay_service_posts: "hssp",
  stay_folios: "hsfo",
  stay_folio_lines: "hsfl",
  identity_contact_points: "idcp",
  identity_addresses: "idad",
  identity_named_contacts: "idnc",
  markets: "mrkt",
  market_locales: "mklo",
  market_currencies: "mkcu",
  fx_rate_sets: "fxrs",
  exchange_rates: "fxrt",
  pricing_categories: "prcg",
  pricing_category_dependencies: "prcd",
  cancellation_policies: "ccpo",
  cancellation_policy_rules: "ccpr",
  price_catalogs: "prca",
  price_schedules: "prsc",
  option_price_rules: "oprr",
  option_unit_price_rules: "oupr",
  option_start_time_rules: "ostr",
  option_unit_tiers: "outi",
  pickup_price_rules: "pkpr",
  dropoff_price_rules: "drpr",
  extra_price_rules: "expr",
  product_extras: "pxtr",
  option_extra_configs: "oexc",
  booking_extras: "bkex",
  product_contact_requirements: "pcre",
  product_booking_questions: "pbqq",
  option_booking_questions: "obqq",
  booking_question_options: "bqop",
  booking_question_unit_triggers: "bqut",
  booking_question_option_triggers: "bqot",
  booking_question_extra_triggers: "bqet",
  booking_answers: "bqan",
  storefront_verification_challenges: "svch",
  offers: "offr",
  offer_participants: "ofpt",
  offer_items: "ofit",
  offer_item_participants: "ofip",
  orders: "ordr",
  order_participants: "orpt",
  order_items: "orit",
  order_item_participants: "orip",
  order_terms: "ortm",
  transaction_pii_access_log: "tpal",
  market_price_catalogs: "mkpc",
  market_product_rules: "mkpr",
  market_channel_rules: "mkcr",
  external_refs: "exrf",
  sellability_snapshots: "sels",
  sellability_snapshot_items: "sesi",
  sellability_policies: "slpo",
  sellability_policy_results: "slpr",
  offer_refresh_runs: "ofrr",
  offer_expiration_events: "ofee",
  sellability_explanations: "slex",

  // --- CONTRACTS ---
  contracts: "cont",
  contract_templates: "ctpl",
  contract_template_versions: "ctpv",
  contract_signatures: "ctsi",
  contract_number_series: "ctns",
  contract_attachments: "ctat",

  // --- POLICIES ---
  policies: "poli",
  policy_versions: "plvr",
  policy_rules: "plrl",
  policy_assignments: "plas",
  policy_acceptances: "plac",

  // --- FINANCE (invoicing extensions) ---
  invoice_number_series: "invs",
  invoice_templates: "invt",
  invoice_renditions: "invr",
  tax_regimes: "txrg",
  invoice_external_refs: "iner",

  // --- PRODUCT MEDIA ---
  product_media: "pmed",
  product_features: "pftr",
  product_faqs: "pfaq",
  product_locations: "ploc",

  // --- PRODUCT TAXONOMY ---
  product_types: "ptyp",
  product_categories: "pctg",
  product_tags: "ptag",

  // --- BOOKING EXTENSIONS ---
  booking_product_details: "bkpd",
  booking_item_product_details: "bipd",
  booking_crm_details: "bkcd",
  booking_transaction_details: "bktd",
  booking_distribution_details: "bkdd",
  booking_participant_travel_details: "bptd",
} as const

export type PrefixKey = keyof typeof PREFIXES
export type PrefixValue = (typeof PREFIXES)[PrefixKey]
