import {
  createFacility,
  deleteFacility,
  getFacilityById,
  listFacilities,
  updateFacility,
} from "./service-core.js"
import {
  createAddress,
  createContactPoint,
  createFacilityContact,
  deleteAddress,
  deleteContactPoint,
  deleteFacilityContact,
  listAddresses,
  listContactPoints,
  listFacilityContacts,
  updateAddress,
  updateContactPoint,
  updateFacilityContact,
} from "./service-identity.js"
import {
  createFacilityFeature,
  createFacilityOperationSchedule,
  deleteFacilityFeature,
  deleteFacilityOperationSchedule,
  listFacilityFeatures,
  listFacilityOperationSchedules,
  updateFacilityFeature,
  updateFacilityOperationSchedule,
} from "./service-operations.js"
import {
  createProperty,
  createPropertyGroup,
  createPropertyGroupMember,
  deleteProperty,
  deletePropertyGroup,
  deletePropertyGroupMember,
  getPropertyById,
  getPropertyGroupById,
  getPropertyGroupMemberById,
  listProperties,
  listPropertyGroupMembers,
  listPropertyGroups,
  updateProperty,
  updatePropertyGroup,
  updatePropertyGroupMember,
} from "./service-properties.js"

export const facilitiesService = {
  listFacilities,
  getFacilityById,
  createFacility,
  updateFacility,
  deleteFacility,
  listContactPoints,
  createContactPoint,
  updateContactPoint,
  deleteContactPoint,
  listAddresses,
  createAddress,
  updateAddress,
  deleteAddress,
  listFacilityContacts,
  createFacilityContact,
  updateFacilityContact,
  deleteFacilityContact,
  listFacilityFeatures,
  createFacilityFeature,
  updateFacilityFeature,
  deleteFacilityFeature,
  listFacilityOperationSchedules,
  createFacilityOperationSchedule,
  updateFacilityOperationSchedule,
  deleteFacilityOperationSchedule,
  listProperties,
  getPropertyById,
  createProperty,
  updateProperty,
  deleteProperty,
  listPropertyGroups,
  getPropertyGroupById,
  createPropertyGroup,
  updatePropertyGroup,
  deletePropertyGroup,
  listPropertyGroupMembers,
  getPropertyGroupMemberById,
  createPropertyGroupMember,
  updatePropertyGroupMember,
  deletePropertyGroupMember,
}
