import { typeId, typeIdRef } from "@voyantjs/db/lib/typeid-column"
import { boolean, date, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core"

export const offersRef = pgTable("offers", {
  id: typeId("offers").primaryKey(),
  offerNumber: text("offer_number").notNull(),
  title: text("title").notNull(),
  status: text("status").notNull(),
  personId: text("person_id"),
  organizationId: text("organization_id"),
  currency: text("currency").notNull(),
  baseCurrency: text("base_currency"),
  totalAmountCents: integer("total_amount_cents").notNull(),
  costAmountCents: integer("cost_amount_cents").notNull(),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  convertedAt: timestamp("converted_at", { withTimezone: true }),
  notes: text("notes"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const offerParticipantsRef = pgTable("offer_participants", {
  id: typeId("offer_participants").primaryKey(),
  offerId: typeIdRef("offer_id").notNull(),
  personId: text("person_id"),
  participantType: text("participant_type").notNull(),
  travelerCategory: text("traveler_category"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email"),
  phone: text("phone"),
  preferredLanguage: text("preferred_language"),
  isPrimary: boolean("is_primary").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const offerItemsRef = pgTable("offer_items", {
  id: typeId("offer_items").primaryKey(),
  offerId: typeIdRef("offer_id").notNull(),
  productId: text("product_id"),
  optionId: text("option_id"),
  unitId: text("unit_id"),
  slotId: text("slot_id"),
  title: text("title").notNull(),
  description: text("description"),
  itemType: text("item_type").notNull(),
  status: text("status").notNull(),
  serviceDate: date("service_date"),
  startsAt: timestamp("starts_at", { withTimezone: true }),
  endsAt: timestamp("ends_at", { withTimezone: true }),
  quantity: integer("quantity").notNull().default(1),
  sellCurrency: text("sell_currency").notNull(),
  unitSellAmountCents: integer("unit_sell_amount_cents"),
  totalSellAmountCents: integer("total_sell_amount_cents"),
  costCurrency: text("cost_currency"),
  unitCostAmountCents: integer("unit_cost_amount_cents"),
  totalCostAmountCents: integer("total_cost_amount_cents"),
  notes: text("notes"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const offerItemParticipantsRef = pgTable("offer_item_participants", {
  id: typeId("offer_item_participants").primaryKey(),
  offerItemId: typeIdRef("offer_item_id").notNull(),
  participantId: typeIdRef("participant_id").notNull(),
  role: text("role").notNull(),
  isPrimary: boolean("is_primary").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
})

export const ordersRef = pgTable("orders", {
  id: typeId("orders").primaryKey(),
  orderNumber: text("order_number").notNull(),
  offerId: typeIdRef("offer_id"),
  title: text("title").notNull(),
  status: text("status").notNull(),
  personId: text("person_id"),
  organizationId: text("organization_id"),
  currency: text("currency").notNull(),
  baseCurrency: text("base_currency"),
  totalAmountCents: integer("total_amount_cents").notNull(),
  costAmountCents: integer("cost_amount_cents").notNull(),
  confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const orderParticipantsRef = pgTable("order_participants", {
  id: typeId("order_participants").primaryKey(),
  orderId: typeIdRef("order_id").notNull(),
  personId: text("person_id"),
  participantType: text("participant_type").notNull(),
  travelerCategory: text("traveler_category"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email"),
  phone: text("phone"),
  preferredLanguage: text("preferred_language"),
  isPrimary: boolean("is_primary").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const orderItemsRef = pgTable("order_items", {
  id: typeId("order_items").primaryKey(),
  orderId: typeIdRef("order_id").notNull(),
  offerItemId: typeIdRef("offer_item_id"),
  productId: text("product_id"),
  optionId: text("option_id"),
  unitId: text("unit_id"),
  slotId: text("slot_id"),
  title: text("title").notNull(),
  description: text("description"),
  itemType: text("item_type").notNull(),
  status: text("status").notNull(),
  serviceDate: date("service_date"),
  startsAt: timestamp("starts_at", { withTimezone: true }),
  endsAt: timestamp("ends_at", { withTimezone: true }),
  quantity: integer("quantity").notNull().default(1),
  sellCurrency: text("sell_currency").notNull(),
  unitSellAmountCents: integer("unit_sell_amount_cents"),
  totalSellAmountCents: integer("total_sell_amount_cents"),
  costCurrency: text("cost_currency"),
  unitCostAmountCents: integer("unit_cost_amount_cents"),
  totalCostAmountCents: integer("total_cost_amount_cents"),
  notes: text("notes"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const orderItemParticipantsRef = pgTable("order_item_participants", {
  id: typeId("order_item_participants").primaryKey(),
  orderItemId: typeIdRef("order_item_id").notNull(),
  participantId: typeIdRef("participant_id").notNull(),
  role: text("role").notNull(),
  isPrimary: boolean("is_primary").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
})

export const bookingTransactionDetailsRef = pgTable("booking_transaction_details", {
  bookingId: text("booking_id").primaryKey(),
  offerId: text("offer_id"),
  orderId: text("order_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})
