import type { Module } from "@voyantjs/core"
import type { HonoModule } from "@voyantjs/hono/module"

import { hospitalityRoutes } from "./routes.js"
import { hospitalityService } from "./service.js"

export type { HospitalityRoutes } from "./routes.js"

export const hospitalityModule: Module = {
  name: "hospitality",
}

export const hospitalityHonoModule: HonoModule = {
  module: hospitalityModule,
  routes: hospitalityRoutes,
}

export type {
  HousekeepingTask,
  MaintenanceBlock,
  MealPlan,
  NewHousekeepingTask,
  NewMaintenanceBlock,
  NewMealPlan,
  NewRatePlan,
  NewRatePlanInventoryOverride,
  NewRatePlanRoomType,
  NewRoomBlock,
  NewRoomTypeRate,
  NewRoomInventory,
  NewRoomType,
  NewRoomTypeBedConfig,
  NewRoomUnit,
  NewRoomUnitStatusEvent,
  NewStayBookingItem,
  NewStayCheckpoint,
  NewStayDailyRate,
  NewStayFolio,
  NewStayFolioLine,
  NewStayOperation,
  NewStayRule,
  NewStayServicePost,
  RatePlan,
  RatePlanInventoryOverride,
  RatePlanRoomType,
  RoomBlock,
  RoomTypeRate,
  RoomInventory,
  RoomType,
  RoomTypeBedConfig,
  RoomUnit,
  RoomUnitStatusEvent,
  StayBookingItem,
  StayCheckpoint,
  StayDailyRate,
  StayFolio,
  StayFolioLine,
  StayOperation,
  StayRule,
  StayServicePost,
} from "./schema.js"
export {
  hospitalityGuaranteeModeEnum,
  hospitalityHousekeepingTaskStatusEnum,
  hospitalityInventoryModeEnum,
  hospitalityMaintenanceBlockStatusEnum,
  hospitalityRoomBlockStatusEnum,
  maintenanceBlocks,
  mealPlans,
  ratePlanChargeFrequencyEnum,
  ratePlanInventoryOverrides,
  ratePlanRoomTypes,
  ratePlans,
  roomBlocks,
  roomInventory,
  roomTypeBedConfigs,
  roomTypeRates,
  roomTypes,
  roomUnitStatusEnum,
  roomUnitStatusEvents,
  roomUnits,
  stayBookingItemStatusEnum,
  stayBookingItems,
  stayCheckpoints,
  stayCheckpointTypeEnum,
  stayDailyRates,
  stayFolioLines,
  stayFolioStatusEnum,
  stayFolios,
  stayOperationStatusEnum,
  stayOperations,
  stayRules,
  stayServicePostKindEnum,
  stayServicePosts,
} from "./schema.js"
export {
  hospitalityGuaranteeModeSchema,
  hospitalityHousekeepingTaskStatusSchema,
  hospitalityInventoryModeSchema,
  hospitalityMaintenanceBlockStatusSchema,
  hospitalityRoomBlockStatusSchema,
  housekeepingTaskListQuerySchema,
  insertHousekeepingTaskSchema,
  insertMaintenanceBlockSchema,
  insertMealPlanSchema,
  insertRatePlanInventoryOverrideSchema,
  insertRatePlanRoomTypeSchema,
  insertRatePlanSchema,
  insertRoomBlockSchema,
  insertRoomInventorySchema,
  insertRoomTypeBedConfigSchema,
  insertRoomTypeRateSchema,
  insertRoomTypeSchema,
  insertRoomUnitSchema,
  insertRoomUnitStatusEventSchema,
  insertStayBookingItemSchema,
  insertStayCheckpointSchema,
  insertStayDailyRateSchema,
  insertStayFolioLineSchema,
  insertStayFolioSchema,
  insertStayOperationSchema,
  insertStayRuleSchema,
  insertStayServicePostSchema,
  maintenanceBlockListQuerySchema,
  mealPlanListQuerySchema,
  ratePlanChargeFrequencySchema,
  ratePlanInventoryOverrideListQuerySchema,
  ratePlanListQuerySchema,
  ratePlanRoomTypeListQuerySchema,
  roomBlockListQuerySchema,
  roomInventoryListQuerySchema,
  roomTypeBedConfigListQuerySchema,
  roomTypeListQuerySchema,
  roomTypeRateListQuerySchema,
  roomUnitListQuerySchema,
  roomUnitStatusEventListQuerySchema,
  roomUnitStatusSchema,
  stayBookingItemListQuerySchema,
  stayBookingItemStatusSchema,
  stayCheckpointListQuerySchema,
  stayCheckpointTypeSchema,
  stayDailyRateListQuerySchema,
  stayFolioLineListQuerySchema,
  stayFolioListQuerySchema,
  stayFolioStatusSchema,
  stayOperationListQuerySchema,
  stayOperationStatusSchema,
  stayRuleListQuerySchema,
  stayServicePostKindSchema,
  stayServicePostListQuerySchema,
  updateHousekeepingTaskSchema,
  updateMaintenanceBlockSchema,
  updateMealPlanSchema,
  updateRatePlanInventoryOverrideSchema,
  updateRatePlanRoomTypeSchema,
  updateRatePlanSchema,
  updateRoomBlockSchema,
  updateRoomInventorySchema,
  updateRoomTypeBedConfigSchema,
  updateRoomTypeRateSchema,
  updateRoomTypeSchema,
  updateRoomUnitSchema,
  updateRoomUnitStatusEventSchema,
  updateStayBookingItemSchema,
  updateStayCheckpointSchema,
  updateStayDailyRateSchema,
  updateStayFolioLineSchema,
  updateStayFolioSchema,
  updateStayOperationSchema,
  updateStayRuleSchema,
  updateStayServicePostSchema,
} from "./validation.js"
export { hospitalityService }
