/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as WorkspaceTeamRouteImport } from './routes/_workspace/team'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as WorkspaceSuppliersIndexRouteImport } from './routes/_workspace/suppliers/index'
import { Route as WorkspaceResourcesIndexRouteImport } from './routes/_workspace/resources/index'
import { Route as WorkspaceProductsIndexRouteImport } from './routes/_workspace/products/index'
import { Route as WorkspaceNotificationsIndexRouteImport } from './routes/_workspace/notifications/index'
import { Route as WorkspaceFinanceIndexRouteImport } from './routes/_workspace/finance/index'
import { Route as WorkspaceDistributionIndexRouteImport } from './routes/_workspace/distribution/index'
import { Route as WorkspaceContactsIndexRouteImport } from './routes/_workspace/contacts/index'
import { Route as WorkspaceBookingsIndexRouteImport } from './routes/_workspace/bookings/index'
import { Route as WorkspaceAvailabilityIndexRouteImport } from './routes/_workspace/availability/index'
import { Route as WorkspaceSuppliersIdRouteImport } from './routes/_workspace/suppliers/$id'
import { Route as WorkspaceResourcesIdRouteImport } from './routes/_workspace/resources/$id'
import { Route as WorkspaceProductsIdRouteImport } from './routes/_workspace/products/$id'
import { Route as WorkspaceNotificationsReminderRunsRouteImport } from './routes/_workspace/notifications/reminder-runs'
import { Route as WorkspaceNotificationsReminderRulesRouteImport } from './routes/_workspace/notifications/reminder-rules'
import { Route as WorkspaceNotificationsDeliveriesRouteImport } from './routes/_workspace/notifications/deliveries'
import { Route as WorkspaceDistributionIdRouteImport } from './routes/_workspace/distribution/$id'
import { Route as WorkspaceContactsIdRouteImport } from './routes/_workspace/contacts/$id'
import { Route as WorkspaceBookingsIdRouteImport } from './routes/_workspace/bookings/$id'
import { Route as WorkspaceAvailabilityIdRouteImport } from './routes/_workspace/availability/$id'
import { Route as WorkspaceNotificationsTemplatesIndexRouteImport } from './routes/_workspace/notifications/templates/index'
import { Route as WorkspaceResourcesPoolsIdRouteImport } from './routes/_workspace/resources/pools/$id'
import { Route as WorkspaceResourcesAssignmentsIdRouteImport } from './routes/_workspace/resources/assignments/$id'
import { Route as WorkspaceResourcesAllocationsIdRouteImport } from './routes/_workspace/resources/allocations/$id'
import { Route as WorkspaceNotificationsTemplatesIdRouteImport } from './routes/_workspace/notifications/templates/$id'
import { Route as WorkspaceFinanceInvoicesIdRouteImport } from './routes/_workspace/finance/invoices/$id'
import { Route as WorkspaceDistributionWebhookEventsIdRouteImport } from './routes/_workspace/distribution/webhook-events/$id'
import { Route as WorkspaceDistributionMappingsIdRouteImport } from './routes/_workspace/distribution/mappings/$id'
import { Route as WorkspaceDistributionContractsIdRouteImport } from './routes/_workspace/distribution/contracts/$id'
import { Route as WorkspaceDistributionCommissionRulesIdRouteImport } from './routes/_workspace/distribution/commission-rules/$id'
import { Route as WorkspaceDistributionBookingLinksIdRouteImport } from './routes/_workspace/distribution/booking-links/$id'
import { Route as WorkspaceAvailabilityStartTimesIdRouteImport } from './routes/_workspace/availability/start-times/$id'
import { Route as WorkspaceAvailabilityRulesIdRouteImport } from './routes/_workspace/availability/rules/$id'

const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceTeamRoute = WorkspaceTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => authRouteRoute,
} as any)
const WorkspaceSuppliersIndexRoute = WorkspaceSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceResourcesIndexRoute = WorkspaceResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProductsIndexRoute = WorkspaceProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceNotificationsIndexRoute =
  WorkspaceNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceIndexRoute = WorkspaceFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceDistributionIndexRoute =
  WorkspaceDistributionIndexRouteImport.update({
    id: '/distribution/',
    path: '/distribution/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceContactsIndexRoute = WorkspaceContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceBookingsIndexRoute = WorkspaceBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAvailabilityIndexRoute =
  WorkspaceAvailabilityIndexRouteImport.update({
    id: '/availability/',
    path: '/availability/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceSuppliersIdRoute = WorkspaceSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceResourcesIdRoute = WorkspaceResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProductsIdRoute = WorkspaceProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceNotificationsReminderRunsRoute =
  WorkspaceNotificationsReminderRunsRouteImport.update({
    id: '/notifications/reminder-runs',
    path: '/notifications/reminder-runs',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsReminderRulesRoute =
  WorkspaceNotificationsReminderRulesRouteImport.update({
    id: '/notifications/reminder-rules',
    path: '/notifications/reminder-rules',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsDeliveriesRoute =
  WorkspaceNotificationsDeliveriesRouteImport.update({
    id: '/notifications/deliveries',
    path: '/notifications/deliveries',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionIdRoute = WorkspaceDistributionIdRouteImport.update({
  id: '/distribution/$id',
  path: '/distribution/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceContactsIdRoute = WorkspaceContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceBookingsIdRoute = WorkspaceBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAvailabilityIdRoute = WorkspaceAvailabilityIdRouteImport.update({
  id: '/availability/$id',
  path: '/availability/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceNotificationsTemplatesIndexRoute =
  WorkspaceNotificationsTemplatesIndexRouteImport.update({
    id: '/notifications/templates/',
    path: '/notifications/templates/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesPoolsIdRoute =
  WorkspaceResourcesPoolsIdRouteImport.update({
    id: '/resources/pools/$id',
    path: '/resources/pools/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAssignmentsIdRoute =
  WorkspaceResourcesAssignmentsIdRouteImport.update({
    id: '/resources/assignments/$id',
    path: '/resources/assignments/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAllocationsIdRoute =
  WorkspaceResourcesAllocationsIdRouteImport.update({
    id: '/resources/allocations/$id',
    path: '/resources/allocations/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceNotificationsTemplatesIdRoute =
  WorkspaceNotificationsTemplatesIdRouteImport.update({
    id: '/notifications/templates/$id',
    path: '/notifications/templates/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceInvoicesIdRoute =
  WorkspaceFinanceInvoicesIdRouteImport.update({
    id: '/finance/invoices/$id',
    path: '/finance/invoices/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionWebhookEventsIdRoute =
  WorkspaceDistributionWebhookEventsIdRouteImport.update({
    id: '/distribution/webhook-events/$id',
    path: '/distribution/webhook-events/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionMappingsIdRoute =
  WorkspaceDistributionMappingsIdRouteImport.update({
    id: '/distribution/mappings/$id',
    path: '/distribution/mappings/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionContractsIdRoute =
  WorkspaceDistributionContractsIdRouteImport.update({
    id: '/distribution/contracts/$id',
    path: '/distribution/contracts/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionCommissionRulesIdRoute =
  WorkspaceDistributionCommissionRulesIdRouteImport.update({
    id: '/distribution/commission-rules/$id',
    path: '/distribution/commission-rules/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDistributionBookingLinksIdRoute =
  WorkspaceDistributionBookingLinksIdRouteImport.update({
    id: '/distribution/booking-links/$id',
    path: '/distribution/booking-links/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityStartTimesIdRoute =
  WorkspaceAvailabilityStartTimesIdRouteImport.update({
    id: '/availability/start-times/$id',
    path: '/availability/start-times/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityRulesIdRoute =
  WorkspaceAvailabilityRulesIdRouteImport.update({
    id: '/availability/rules/$id',
    path: '/availability/rules/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/team': typeof WorkspaceTeamRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/contacts/$id': typeof WorkspaceContactsIdRoute
  '/distribution/$id': typeof WorkspaceDistributionIdRoute
  '/notifications/deliveries': typeof WorkspaceNotificationsDeliveriesRoute
  '/notifications/reminder-rules': typeof WorkspaceNotificationsReminderRulesRoute
  '/notifications/reminder-runs': typeof WorkspaceNotificationsReminderRunsRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/bookings/': typeof WorkspaceBookingsIndexRoute
  '/contacts/': typeof WorkspaceContactsIndexRoute
  '/distribution/': typeof WorkspaceDistributionIndexRoute
  '/finance/': typeof WorkspaceFinanceIndexRoute
  '/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/products/': typeof WorkspaceProductsIndexRoute
  '/resources/': typeof WorkspaceResourcesIndexRoute
  '/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/distribution/booking-links/$id': typeof WorkspaceDistributionBookingLinksIdRoute
  '/distribution/commission-rules/$id': typeof WorkspaceDistributionCommissionRulesIdRoute
  '/distribution/contracts/$id': typeof WorkspaceDistributionContractsIdRoute
  '/distribution/mappings/$id': typeof WorkspaceDistributionMappingsIdRoute
  '/distribution/webhook-events/$id': typeof WorkspaceDistributionWebhookEventsIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/notifications/templates/$id': typeof WorkspaceNotificationsTemplatesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/notifications/templates/': typeof WorkspaceNotificationsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/team': typeof WorkspaceTeamRoute
  '/': typeof WorkspaceIndexRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/contacts/$id': typeof WorkspaceContactsIdRoute
  '/distribution/$id': typeof WorkspaceDistributionIdRoute
  '/notifications/deliveries': typeof WorkspaceNotificationsDeliveriesRoute
  '/notifications/reminder-rules': typeof WorkspaceNotificationsReminderRulesRoute
  '/notifications/reminder-runs': typeof WorkspaceNotificationsReminderRunsRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/availability': typeof WorkspaceAvailabilityIndexRoute
  '/bookings': typeof WorkspaceBookingsIndexRoute
  '/contacts': typeof WorkspaceContactsIndexRoute
  '/distribution': typeof WorkspaceDistributionIndexRoute
  '/finance': typeof WorkspaceFinanceIndexRoute
  '/notifications': typeof WorkspaceNotificationsIndexRoute
  '/products': typeof WorkspaceProductsIndexRoute
  '/resources': typeof WorkspaceResourcesIndexRoute
  '/suppliers': typeof WorkspaceSuppliersIndexRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/distribution/booking-links/$id': typeof WorkspaceDistributionBookingLinksIdRoute
  '/distribution/commission-rules/$id': typeof WorkspaceDistributionCommissionRulesIdRoute
  '/distribution/contracts/$id': typeof WorkspaceDistributionContractsIdRoute
  '/distribution/mappings/$id': typeof WorkspaceDistributionMappingsIdRoute
  '/distribution/webhook-events/$id': typeof WorkspaceDistributionWebhookEventsIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/notifications/templates/$id': typeof WorkspaceNotificationsTemplatesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/notifications/templates': typeof WorkspaceNotificationsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_workspace/team': typeof WorkspaceTeamRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/_workspace/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/_workspace/contacts/$id': typeof WorkspaceContactsIdRoute
  '/_workspace/distribution/$id': typeof WorkspaceDistributionIdRoute
  '/_workspace/notifications/deliveries': typeof WorkspaceNotificationsDeliveriesRoute
  '/_workspace/notifications/reminder-rules': typeof WorkspaceNotificationsReminderRulesRoute
  '/_workspace/notifications/reminder-runs': typeof WorkspaceNotificationsReminderRunsRoute
  '/_workspace/products/$id': typeof WorkspaceProductsIdRoute
  '/_workspace/resources/$id': typeof WorkspaceResourcesIdRoute
  '/_workspace/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/_workspace/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/_workspace/bookings/': typeof WorkspaceBookingsIndexRoute
  '/_workspace/contacts/': typeof WorkspaceContactsIndexRoute
  '/_workspace/distribution/': typeof WorkspaceDistributionIndexRoute
  '/_workspace/finance/': typeof WorkspaceFinanceIndexRoute
  '/_workspace/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/_workspace/products/': typeof WorkspaceProductsIndexRoute
  '/_workspace/resources/': typeof WorkspaceResourcesIndexRoute
  '/_workspace/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/_workspace/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/_workspace/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/_workspace/distribution/booking-links/$id': typeof WorkspaceDistributionBookingLinksIdRoute
  '/_workspace/distribution/commission-rules/$id': typeof WorkspaceDistributionCommissionRulesIdRoute
  '/_workspace/distribution/contracts/$id': typeof WorkspaceDistributionContractsIdRoute
  '/_workspace/distribution/mappings/$id': typeof WorkspaceDistributionMappingsIdRoute
  '/_workspace/distribution/webhook-events/$id': typeof WorkspaceDistributionWebhookEventsIdRoute
  '/_workspace/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/_workspace/notifications/templates/$id': typeof WorkspaceNotificationsTemplatesIdRoute
  '/_workspace/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/_workspace/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/_workspace/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
  '/_workspace/notifications/templates/': typeof WorkspaceNotificationsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/team'
    | '/availability/$id'
    | '/bookings/$id'
    | '/contacts/$id'
    | '/distribution/$id'
    | '/notifications/deliveries'
    | '/notifications/reminder-rules'
    | '/notifications/reminder-runs'
    | '/products/$id'
    | '/resources/$id'
    | '/suppliers/$id'
    | '/availability/'
    | '/bookings/'
    | '/contacts/'
    | '/distribution/'
    | '/finance/'
    | '/notifications/'
    | '/products/'
    | '/resources/'
    | '/suppliers/'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/distribution/booking-links/$id'
    | '/distribution/commission-rules/$id'
    | '/distribution/contracts/$id'
    | '/distribution/mappings/$id'
    | '/distribution/webhook-events/$id'
    | '/finance/invoices/$id'
    | '/notifications/templates/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
    | '/notifications/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/team'
    | '/'
    | '/availability/$id'
    | '/bookings/$id'
    | '/contacts/$id'
    | '/distribution/$id'
    | '/notifications/deliveries'
    | '/notifications/reminder-rules'
    | '/notifications/reminder-runs'
    | '/products/$id'
    | '/resources/$id'
    | '/suppliers/$id'
    | '/availability'
    | '/bookings'
    | '/contacts'
    | '/distribution'
    | '/finance'
    | '/notifications'
    | '/products'
    | '/resources'
    | '/suppliers'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/distribution/booking-links/$id'
    | '/distribution/commission-rules/$id'
    | '/distribution/contracts/$id'
    | '/distribution/mappings/$id'
    | '/distribution/webhook-events/$id'
    | '/finance/invoices/$id'
    | '/notifications/templates/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
    | '/notifications/templates'
  id:
    | '__root__'
    | '/(auth)'
    | '/_workspace'
    | '/(auth)/accept-invitation'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/onboarding'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/_workspace/team'
    | '/_workspace/'
    | '/_workspace/availability/$id'
    | '/_workspace/bookings/$id'
    | '/_workspace/contacts/$id'
    | '/_workspace/distribution/$id'
    | '/_workspace/notifications/deliveries'
    | '/_workspace/notifications/reminder-rules'
    | '/_workspace/notifications/reminder-runs'
    | '/_workspace/products/$id'
    | '/_workspace/resources/$id'
    | '/_workspace/suppliers/$id'
    | '/_workspace/availability/'
    | '/_workspace/bookings/'
    | '/_workspace/contacts/'
    | '/_workspace/distribution/'
    | '/_workspace/finance/'
    | '/_workspace/notifications/'
    | '/_workspace/products/'
    | '/_workspace/resources/'
    | '/_workspace/suppliers/'
    | '/_workspace/availability/rules/$id'
    | '/_workspace/availability/start-times/$id'
    | '/_workspace/distribution/booking-links/$id'
    | '/_workspace/distribution/commission-rules/$id'
    | '/_workspace/distribution/contracts/$id'
    | '/_workspace/distribution/mappings/$id'
    | '/_workspace/distribution/webhook-events/$id'
    | '/_workspace/finance/invoices/$id'
    | '/_workspace/notifications/templates/$id'
    | '/_workspace/resources/allocations/$id'
    | '/_workspace/resources/assignments/$id'
    | '/_workspace/resources/pools/$id'
    | '/_workspace/notifications/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/team': {
      id: '/_workspace/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof WorkspaceTeamRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_workspace/suppliers/': {
      id: '/_workspace/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof WorkspaceSuppliersIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/': {
      id: '/_workspace/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof WorkspaceResourcesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/': {
      id: '/_workspace/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof WorkspaceProductsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/': {
      id: '/_workspace/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof WorkspaceNotificationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/': {
      id: '/_workspace/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof WorkspaceFinanceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/': {
      id: '/_workspace/distribution/'
      path: '/distribution'
      fullPath: '/distribution/'
      preLoaderRoute: typeof WorkspaceDistributionIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/contacts/': {
      id: '/_workspace/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof WorkspaceContactsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/': {
      id: '/_workspace/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof WorkspaceBookingsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/': {
      id: '/_workspace/availability/'
      path: '/availability'
      fullPath: '/availability/'
      preLoaderRoute: typeof WorkspaceAvailabilityIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/suppliers/$id': {
      id: '/_workspace/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof WorkspaceSuppliersIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/$id': {
      id: '/_workspace/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof WorkspaceResourcesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/$id': {
      id: '/_workspace/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof WorkspaceProductsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/reminder-runs': {
      id: '/_workspace/notifications/reminder-runs'
      path: '/notifications/reminder-runs'
      fullPath: '/notifications/reminder-runs'
      preLoaderRoute: typeof WorkspaceNotificationsReminderRunsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/reminder-rules': {
      id: '/_workspace/notifications/reminder-rules'
      path: '/notifications/reminder-rules'
      fullPath: '/notifications/reminder-rules'
      preLoaderRoute: typeof WorkspaceNotificationsReminderRulesRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/deliveries': {
      id: '/_workspace/notifications/deliveries'
      path: '/notifications/deliveries'
      fullPath: '/notifications/deliveries'
      preLoaderRoute: typeof WorkspaceNotificationsDeliveriesRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/$id': {
      id: '/_workspace/distribution/$id'
      path: '/distribution/$id'
      fullPath: '/distribution/$id'
      preLoaderRoute: typeof WorkspaceDistributionIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/contacts/$id': {
      id: '/_workspace/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof WorkspaceContactsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/$id': {
      id: '/_workspace/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof WorkspaceBookingsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/$id': {
      id: '/_workspace/availability/$id'
      path: '/availability/$id'
      fullPath: '/availability/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/templates/': {
      id: '/_workspace/notifications/templates/'
      path: '/notifications/templates'
      fullPath: '/notifications/templates/'
      preLoaderRoute: typeof WorkspaceNotificationsTemplatesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/pools/$id': {
      id: '/_workspace/resources/pools/$id'
      path: '/resources/pools/$id'
      fullPath: '/resources/pools/$id'
      preLoaderRoute: typeof WorkspaceResourcesPoolsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/assignments/$id': {
      id: '/_workspace/resources/assignments/$id'
      path: '/resources/assignments/$id'
      fullPath: '/resources/assignments/$id'
      preLoaderRoute: typeof WorkspaceResourcesAssignmentsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/allocations/$id': {
      id: '/_workspace/resources/allocations/$id'
      path: '/resources/allocations/$id'
      fullPath: '/resources/allocations/$id'
      preLoaderRoute: typeof WorkspaceResourcesAllocationsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/notifications/templates/$id': {
      id: '/_workspace/notifications/templates/$id'
      path: '/notifications/templates/$id'
      fullPath: '/notifications/templates/$id'
      preLoaderRoute: typeof WorkspaceNotificationsTemplatesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/invoices/$id': {
      id: '/_workspace/finance/invoices/$id'
      path: '/finance/invoices/$id'
      fullPath: '/finance/invoices/$id'
      preLoaderRoute: typeof WorkspaceFinanceInvoicesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/webhook-events/$id': {
      id: '/_workspace/distribution/webhook-events/$id'
      path: '/distribution/webhook-events/$id'
      fullPath: '/distribution/webhook-events/$id'
      preLoaderRoute: typeof WorkspaceDistributionWebhookEventsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/mappings/$id': {
      id: '/_workspace/distribution/mappings/$id'
      path: '/distribution/mappings/$id'
      fullPath: '/distribution/mappings/$id'
      preLoaderRoute: typeof WorkspaceDistributionMappingsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/contracts/$id': {
      id: '/_workspace/distribution/contracts/$id'
      path: '/distribution/contracts/$id'
      fullPath: '/distribution/contracts/$id'
      preLoaderRoute: typeof WorkspaceDistributionContractsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/commission-rules/$id': {
      id: '/_workspace/distribution/commission-rules/$id'
      path: '/distribution/commission-rules/$id'
      fullPath: '/distribution/commission-rules/$id'
      preLoaderRoute: typeof WorkspaceDistributionCommissionRulesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/distribution/booking-links/$id': {
      id: '/_workspace/distribution/booking-links/$id'
      path: '/distribution/booking-links/$id'
      fullPath: '/distribution/booking-links/$id'
      preLoaderRoute: typeof WorkspaceDistributionBookingLinksIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/start-times/$id': {
      id: '/_workspace/availability/start-times/$id'
      path: '/availability/start-times/$id'
      fullPath: '/availability/start-times/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityStartTimesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/rules/$id': {
      id: '/_workspace/availability/rules/$id'
      path: '/availability/rules/$id'
      fullPath: '/availability/rules/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityRulesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOnboardingRoute: authOnboardingRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface WorkspaceRouteRouteChildren {
  WorkspaceTeamRoute: typeof WorkspaceTeamRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceAvailabilityIdRoute: typeof WorkspaceAvailabilityIdRoute
  WorkspaceBookingsIdRoute: typeof WorkspaceBookingsIdRoute
  WorkspaceContactsIdRoute: typeof WorkspaceContactsIdRoute
  WorkspaceDistributionIdRoute: typeof WorkspaceDistributionIdRoute
  WorkspaceNotificationsDeliveriesRoute: typeof WorkspaceNotificationsDeliveriesRoute
  WorkspaceNotificationsReminderRulesRoute: typeof WorkspaceNotificationsReminderRulesRoute
  WorkspaceNotificationsReminderRunsRoute: typeof WorkspaceNotificationsReminderRunsRoute
  WorkspaceProductsIdRoute: typeof WorkspaceProductsIdRoute
  WorkspaceResourcesIdRoute: typeof WorkspaceResourcesIdRoute
  WorkspaceSuppliersIdRoute: typeof WorkspaceSuppliersIdRoute
  WorkspaceAvailabilityIndexRoute: typeof WorkspaceAvailabilityIndexRoute
  WorkspaceBookingsIndexRoute: typeof WorkspaceBookingsIndexRoute
  WorkspaceContactsIndexRoute: typeof WorkspaceContactsIndexRoute
  WorkspaceDistributionIndexRoute: typeof WorkspaceDistributionIndexRoute
  WorkspaceFinanceIndexRoute: typeof WorkspaceFinanceIndexRoute
  WorkspaceNotificationsIndexRoute: typeof WorkspaceNotificationsIndexRoute
  WorkspaceProductsIndexRoute: typeof WorkspaceProductsIndexRoute
  WorkspaceResourcesIndexRoute: typeof WorkspaceResourcesIndexRoute
  WorkspaceSuppliersIndexRoute: typeof WorkspaceSuppliersIndexRoute
  WorkspaceAvailabilityRulesIdRoute: typeof WorkspaceAvailabilityRulesIdRoute
  WorkspaceAvailabilityStartTimesIdRoute: typeof WorkspaceAvailabilityStartTimesIdRoute
  WorkspaceDistributionBookingLinksIdRoute: typeof WorkspaceDistributionBookingLinksIdRoute
  WorkspaceDistributionCommissionRulesIdRoute: typeof WorkspaceDistributionCommissionRulesIdRoute
  WorkspaceDistributionContractsIdRoute: typeof WorkspaceDistributionContractsIdRoute
  WorkspaceDistributionMappingsIdRoute: typeof WorkspaceDistributionMappingsIdRoute
  WorkspaceDistributionWebhookEventsIdRoute: typeof WorkspaceDistributionWebhookEventsIdRoute
  WorkspaceFinanceInvoicesIdRoute: typeof WorkspaceFinanceInvoicesIdRoute
  WorkspaceNotificationsTemplatesIdRoute: typeof WorkspaceNotificationsTemplatesIdRoute
  WorkspaceResourcesAllocationsIdRoute: typeof WorkspaceResourcesAllocationsIdRoute
  WorkspaceResourcesAssignmentsIdRoute: typeof WorkspaceResourcesAssignmentsIdRoute
  WorkspaceResourcesPoolsIdRoute: typeof WorkspaceResourcesPoolsIdRoute
  WorkspaceNotificationsTemplatesIndexRoute: typeof WorkspaceNotificationsTemplatesIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceTeamRoute: WorkspaceTeamRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceAvailabilityIdRoute: WorkspaceAvailabilityIdRoute,
  WorkspaceBookingsIdRoute: WorkspaceBookingsIdRoute,
  WorkspaceContactsIdRoute: WorkspaceContactsIdRoute,
  WorkspaceDistributionIdRoute: WorkspaceDistributionIdRoute,
  WorkspaceNotificationsDeliveriesRoute: WorkspaceNotificationsDeliveriesRoute,
  WorkspaceNotificationsReminderRulesRoute:
    WorkspaceNotificationsReminderRulesRoute,
  WorkspaceNotificationsReminderRunsRoute:
    WorkspaceNotificationsReminderRunsRoute,
  WorkspaceProductsIdRoute: WorkspaceProductsIdRoute,
  WorkspaceResourcesIdRoute: WorkspaceResourcesIdRoute,
  WorkspaceSuppliersIdRoute: WorkspaceSuppliersIdRoute,
  WorkspaceAvailabilityIndexRoute: WorkspaceAvailabilityIndexRoute,
  WorkspaceBookingsIndexRoute: WorkspaceBookingsIndexRoute,
  WorkspaceContactsIndexRoute: WorkspaceContactsIndexRoute,
  WorkspaceDistributionIndexRoute: WorkspaceDistributionIndexRoute,
  WorkspaceFinanceIndexRoute: WorkspaceFinanceIndexRoute,
  WorkspaceNotificationsIndexRoute: WorkspaceNotificationsIndexRoute,
  WorkspaceProductsIndexRoute: WorkspaceProductsIndexRoute,
  WorkspaceResourcesIndexRoute: WorkspaceResourcesIndexRoute,
  WorkspaceSuppliersIndexRoute: WorkspaceSuppliersIndexRoute,
  WorkspaceAvailabilityRulesIdRoute: WorkspaceAvailabilityRulesIdRoute,
  WorkspaceAvailabilityStartTimesIdRoute:
    WorkspaceAvailabilityStartTimesIdRoute,
  WorkspaceDistributionBookingLinksIdRoute:
    WorkspaceDistributionBookingLinksIdRoute,
  WorkspaceDistributionCommissionRulesIdRoute:
    WorkspaceDistributionCommissionRulesIdRoute,
  WorkspaceDistributionContractsIdRoute: WorkspaceDistributionContractsIdRoute,
  WorkspaceDistributionMappingsIdRoute: WorkspaceDistributionMappingsIdRoute,
  WorkspaceDistributionWebhookEventsIdRoute:
    WorkspaceDistributionWebhookEventsIdRoute,
  WorkspaceFinanceInvoicesIdRoute: WorkspaceFinanceInvoicesIdRoute,
  WorkspaceNotificationsTemplatesIdRoute:
    WorkspaceNotificationsTemplatesIdRoute,
  WorkspaceResourcesAllocationsIdRoute: WorkspaceResourcesAllocationsIdRoute,
  WorkspaceResourcesAssignmentsIdRoute: WorkspaceResourcesAssignmentsIdRoute,
  WorkspaceResourcesPoolsIdRoute: WorkspaceResourcesPoolsIdRoute,
  WorkspaceNotificationsTemplatesIndexRoute:
    WorkspaceNotificationsTemplatesIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
