import {
  createSupplier,
  deleteSupplier,
  getSupplierById,
  listSuppliers,
  updateSupplier,
} from "./service-core.js"
import {
  createAddress,
  createContactPoint,
  createNamedContact,
  deleteAddress,
  deleteContactPoint,
  deleteNamedContact,
  listAddresses,
  listContactPoints,
  listNamedContacts,
  updateAddress,
  updateContactPoint,
  updateNamedContact,
} from "./service-identity.js"
import {
  createAvailability,
  createContract,
  createNote,
  createRate,
  createService,
  deleteContract,
  deleteRate,
  deleteService,
  listAvailability,
  listContracts,
  listNotes,
  listRates,
  listServices,
  updateContract,
  updateRate,
  updateService,
} from "./service-operations.js"

export const suppliersService = {
  listSuppliers,
  getSupplierById,
  createSupplier,
  updateSupplier,
  deleteSupplier,
  listContactPoints,
  listNamedContacts,
  createNamedContact,
  updateNamedContact,
  deleteNamedContact,
  createContactPoint,
  updateContactPoint,
  deleteContactPoint,
  listAddresses,
  createAddress,
  updateAddress,
  deleteAddress,
  listServices,
  createService,
  updateService,
  deleteService,
  listRates,
  createRate,
  updateRate,
  deleteRate,
  listNotes,
  createNote,
  listAvailability,
  createAvailability,
  listContracts,
  createContract,
  updateContract,
  deleteContract,
}
