/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAcceptInviteRouteImport } from './routes/(auth)/accept-invite'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as WorkspaceSuppliersIndexRouteImport } from './routes/_workspace/suppliers/index'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as WorkspaceResourcesIndexRouteImport } from './routes/_workspace/resources/index'
import { Route as WorkspaceProductsIndexRouteImport } from './routes/_workspace/products/index'
import { Route as WorkspacePeopleIndexRouteImport } from './routes/_workspace/people/index'
import { Route as WorkspaceOrganizationsIndexRouteImport } from './routes/_workspace/organizations/index'
import { Route as WorkspaceFinanceIndexRouteImport } from './routes/_workspace/finance/index'
import { Route as WorkspaceBookingsIndexRouteImport } from './routes/_workspace/bookings/index'
import { Route as WorkspaceAvailabilityIndexRouteImport } from './routes/_workspace/availability/index'
import { Route as WorkspaceSuppliersIdRouteImport } from './routes/_workspace/suppliers/$id'
import { Route as WorkspaceSettingsProductTypesRouteImport } from './routes/_workspace/settings/product-types'
import { Route as WorkspaceSettingsProductTagsRouteImport } from './routes/_workspace/settings/product-tags'
import { Route as WorkspaceSettingsPricingCategoriesRouteImport } from './routes/_workspace/settings/pricing-categories'
import { Route as WorkspaceSettingsPriceCatalogsRouteImport } from './routes/_workspace/settings/price-catalogs'
import { Route as WorkspaceSettingsChannelsRouteImport } from './routes/_workspace/settings/channels'
import { Route as WorkspaceResourcesIdRouteImport } from './routes/_workspace/resources/$id'
import { Route as WorkspaceProductsCategoriesRouteImport } from './routes/_workspace/products/categories'
import { Route as WorkspaceProductsIdRouteImport } from './routes/_workspace/products/$id'
import { Route as WorkspacePeopleIdRouteImport } from './routes/_workspace/people/$id'
import { Route as WorkspaceOrganizationsIdRouteImport } from './routes/_workspace/organizations/$id'
import { Route as WorkspaceBookingsIdRouteImport } from './routes/_workspace/bookings/$id'
import { Route as WorkspaceAvailabilityIdRouteImport } from './routes/_workspace/availability/$id'
import { Route as WorkspaceResourcesPoolsIdRouteImport } from './routes/_workspace/resources/pools/$id'
import { Route as WorkspaceResourcesAssignmentsIdRouteImport } from './routes/_workspace/resources/assignments/$id'
import { Route as WorkspaceResourcesAllocationsIdRouteImport } from './routes/_workspace/resources/allocations/$id'
import { Route as WorkspaceFinanceInvoicesIdRouteImport } from './routes/_workspace/finance/invoices/$id'
import { Route as WorkspaceAvailabilityStartTimesIdRouteImport } from './routes/_workspace/availability/start-times/$id'
import { Route as WorkspaceAvailabilityRulesIdRouteImport } from './routes/_workspace/availability/rules/$id'

const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInviteRoute = authAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => authRouteRoute,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => authRouteRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSuppliersIndexRoute = WorkspaceSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceResourcesIndexRoute = WorkspaceResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProductsIndexRoute = WorkspaceProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePeopleIndexRoute = WorkspacePeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOrganizationsIndexRoute =
  WorkspaceOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceIndexRoute = WorkspaceFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceBookingsIndexRoute = WorkspaceBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAvailabilityIndexRoute =
  WorkspaceAvailabilityIndexRouteImport.update({
    id: '/availability/',
    path: '/availability/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceSuppliersIdRoute = WorkspaceSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsProductTypesRoute =
  WorkspaceSettingsProductTypesRouteImport.update({
    id: '/product-types',
    path: '/product-types',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsProductTagsRoute =
  WorkspaceSettingsProductTagsRouteImport.update({
    id: '/product-tags',
    path: '/product-tags',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPricingCategoriesRoute =
  WorkspaceSettingsPricingCategoriesRouteImport.update({
    id: '/pricing-categories',
    path: '/pricing-categories',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsPriceCatalogsRoute =
  WorkspaceSettingsPriceCatalogsRouteImport.update({
    id: '/price-catalogs',
    path: '/price-catalogs',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsChannelsRoute =
  WorkspaceSettingsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceResourcesIdRoute = WorkspaceResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProductsCategoriesRoute =
  WorkspaceProductsCategoriesRouteImport.update({
    id: '/products/categories',
    path: '/products/categories',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceProductsIdRoute = WorkspaceProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePeopleIdRoute = WorkspacePeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOrganizationsIdRoute =
  WorkspaceOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceBookingsIdRoute = WorkspaceBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAvailabilityIdRoute = WorkspaceAvailabilityIdRouteImport.update({
  id: '/availability/$id',
  path: '/availability/$id',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceResourcesPoolsIdRoute =
  WorkspaceResourcesPoolsIdRouteImport.update({
    id: '/resources/pools/$id',
    path: '/resources/pools/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAssignmentsIdRoute =
  WorkspaceResourcesAssignmentsIdRouteImport.update({
    id: '/resources/assignments/$id',
    path: '/resources/assignments/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceResourcesAllocationsIdRoute =
  WorkspaceResourcesAllocationsIdRouteImport.update({
    id: '/resources/allocations/$id',
    path: '/resources/allocations/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceFinanceInvoicesIdRoute =
  WorkspaceFinanceInvoicesIdRouteImport.update({
    id: '/finance/invoices/$id',
    path: '/finance/invoices/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityStartTimesIdRoute =
  WorkspaceAvailabilityStartTimesIdRouteImport.update({
    id: '/availability/start-times/$id',
    path: '/availability/start-times/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAvailabilityRulesIdRoute =
  WorkspaceAvailabilityRulesIdRouteImport.update({
    id: '/availability/rules/$id',
    path: '/availability/rules/$id',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/people/$id': typeof WorkspacePeopleIdRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/products/categories': typeof WorkspaceProductsCategoriesRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/bookings/': typeof WorkspaceBookingsIndexRoute
  '/finance/': typeof WorkspaceFinanceIndexRoute
  '/organizations/': typeof WorkspaceOrganizationsIndexRoute
  '/people/': typeof WorkspacePeopleIndexRoute
  '/products/': typeof WorkspaceProductsIndexRoute
  '/resources/': typeof WorkspaceResourcesIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/accept-invite': typeof authAcceptInviteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof WorkspaceIndexRoute
  '/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/people/$id': typeof WorkspacePeopleIdRoute
  '/products/$id': typeof WorkspaceProductsIdRoute
  '/products/categories': typeof WorkspaceProductsCategoriesRoute
  '/resources/$id': typeof WorkspaceResourcesIdRoute
  '/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/availability': typeof WorkspaceAvailabilityIndexRoute
  '/bookings': typeof WorkspaceBookingsIndexRoute
  '/finance': typeof WorkspaceFinanceIndexRoute
  '/organizations': typeof WorkspaceOrganizationsIndexRoute
  '/people': typeof WorkspacePeopleIndexRoute
  '/products': typeof WorkspaceProductsIndexRoute
  '/resources': typeof WorkspaceResourcesIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/suppliers': typeof WorkspaceSuppliersIndexRoute
  '/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/accept-invite': typeof authAcceptInviteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/availability/$id': typeof WorkspaceAvailabilityIdRoute
  '/_workspace/bookings/$id': typeof WorkspaceBookingsIdRoute
  '/_workspace/organizations/$id': typeof WorkspaceOrganizationsIdRoute
  '/_workspace/people/$id': typeof WorkspacePeopleIdRoute
  '/_workspace/products/$id': typeof WorkspaceProductsIdRoute
  '/_workspace/products/categories': typeof WorkspaceProductsCategoriesRoute
  '/_workspace/resources/$id': typeof WorkspaceResourcesIdRoute
  '/_workspace/settings/channels': typeof WorkspaceSettingsChannelsRoute
  '/_workspace/settings/price-catalogs': typeof WorkspaceSettingsPriceCatalogsRoute
  '/_workspace/settings/pricing-categories': typeof WorkspaceSettingsPricingCategoriesRoute
  '/_workspace/settings/product-tags': typeof WorkspaceSettingsProductTagsRoute
  '/_workspace/settings/product-types': typeof WorkspaceSettingsProductTypesRoute
  '/_workspace/suppliers/$id': typeof WorkspaceSuppliersIdRoute
  '/_workspace/availability/': typeof WorkspaceAvailabilityIndexRoute
  '/_workspace/bookings/': typeof WorkspaceBookingsIndexRoute
  '/_workspace/finance/': typeof WorkspaceFinanceIndexRoute
  '/_workspace/organizations/': typeof WorkspaceOrganizationsIndexRoute
  '/_workspace/people/': typeof WorkspacePeopleIndexRoute
  '/_workspace/products/': typeof WorkspaceProductsIndexRoute
  '/_workspace/resources/': typeof WorkspaceResourcesIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/_workspace/suppliers/': typeof WorkspaceSuppliersIndexRoute
  '/_workspace/availability/rules/$id': typeof WorkspaceAvailabilityRulesIdRoute
  '/_workspace/availability/start-times/$id': typeof WorkspaceAvailabilityStartTimesIdRoute
  '/_workspace/finance/invoices/$id': typeof WorkspaceFinanceInvoicesIdRoute
  '/_workspace/resources/allocations/$id': typeof WorkspaceResourcesAllocationsIdRoute
  '/_workspace/resources/assignments/$id': typeof WorkspaceResourcesAssignmentsIdRoute
  '/_workspace/resources/pools/$id': typeof WorkspaceResourcesPoolsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/availability/$id'
    | '/bookings/$id'
    | '/organizations/$id'
    | '/people/$id'
    | '/products/$id'
    | '/products/categories'
    | '/resources/$id'
    | '/settings/channels'
    | '/settings/price-catalogs'
    | '/settings/pricing-categories'
    | '/settings/product-tags'
    | '/settings/product-types'
    | '/suppliers/$id'
    | '/availability/'
    | '/bookings/'
    | '/finance/'
    | '/organizations/'
    | '/people/'
    | '/products/'
    | '/resources/'
    | '/settings/'
    | '/suppliers/'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/finance/invoices/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/accept-invite'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/'
    | '/availability/$id'
    | '/bookings/$id'
    | '/organizations/$id'
    | '/people/$id'
    | '/products/$id'
    | '/products/categories'
    | '/resources/$id'
    | '/settings/channels'
    | '/settings/price-catalogs'
    | '/settings/pricing-categories'
    | '/settings/product-tags'
    | '/settings/product-types'
    | '/suppliers/$id'
    | '/availability'
    | '/bookings'
    | '/finance'
    | '/organizations'
    | '/people'
    | '/products'
    | '/resources'
    | '/settings'
    | '/suppliers'
    | '/availability/rules/$id'
    | '/availability/start-times/$id'
    | '/finance/invoices/$id'
    | '/resources/allocations/$id'
    | '/resources/assignments/$id'
    | '/resources/pools/$id'
  id:
    | '__root__'
    | '/(auth)'
    | '/_workspace'
    | '/_workspace/settings'
    | '/(auth)/accept-invitation'
    | '/(auth)/accept-invite'
    | '/(auth)/forgot-password'
    | '/(auth)/onboarding'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/_workspace/'
    | '/_workspace/availability/$id'
    | '/_workspace/bookings/$id'
    | '/_workspace/organizations/$id'
    | '/_workspace/people/$id'
    | '/_workspace/products/$id'
    | '/_workspace/products/categories'
    | '/_workspace/resources/$id'
    | '/_workspace/settings/channels'
    | '/_workspace/settings/price-catalogs'
    | '/_workspace/settings/pricing-categories'
    | '/_workspace/settings/product-tags'
    | '/_workspace/settings/product-types'
    | '/_workspace/suppliers/$id'
    | '/_workspace/availability/'
    | '/_workspace/bookings/'
    | '/_workspace/finance/'
    | '/_workspace/organizations/'
    | '/_workspace/people/'
    | '/_workspace/products/'
    | '/_workspace/resources/'
    | '/_workspace/settings/'
    | '/_workspace/suppliers/'
    | '/_workspace/availability/rules/$id'
    | '/_workspace/availability/start-times/$id'
    | '/_workspace/finance/invoices/$id'
    | '/_workspace/resources/allocations/$id'
    | '/_workspace/resources/assignments/$id'
    | '/_workspace/resources/pools/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invite': {
      id: '/(auth)/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof authAcceptInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/suppliers/': {
      id: '/_workspace/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof WorkspaceSuppliersIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/resources/': {
      id: '/_workspace/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof WorkspaceResourcesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/': {
      id: '/_workspace/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof WorkspaceProductsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/people/': {
      id: '/_workspace/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof WorkspacePeopleIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/organizations/': {
      id: '/_workspace/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof WorkspaceOrganizationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/': {
      id: '/_workspace/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof WorkspaceFinanceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/': {
      id: '/_workspace/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof WorkspaceBookingsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/': {
      id: '/_workspace/availability/'
      path: '/availability'
      fullPath: '/availability/'
      preLoaderRoute: typeof WorkspaceAvailabilityIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/suppliers/$id': {
      id: '/_workspace/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof WorkspaceSuppliersIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/product-types': {
      id: '/_workspace/settings/product-types'
      path: '/product-types'
      fullPath: '/settings/product-types'
      preLoaderRoute: typeof WorkspaceSettingsProductTypesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/product-tags': {
      id: '/_workspace/settings/product-tags'
      path: '/product-tags'
      fullPath: '/settings/product-tags'
      preLoaderRoute: typeof WorkspaceSettingsProductTagsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/pricing-categories': {
      id: '/_workspace/settings/pricing-categories'
      path: '/pricing-categories'
      fullPath: '/settings/pricing-categories'
      preLoaderRoute: typeof WorkspaceSettingsPricingCategoriesRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/price-catalogs': {
      id: '/_workspace/settings/price-catalogs'
      path: '/price-catalogs'
      fullPath: '/settings/price-catalogs'
      preLoaderRoute: typeof WorkspaceSettingsPriceCatalogsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/channels': {
      id: '/_workspace/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof WorkspaceSettingsChannelsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/resources/$id': {
      id: '/_workspace/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof WorkspaceResourcesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/categories': {
      id: '/_workspace/products/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof WorkspaceProductsCategoriesRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/products/$id': {
      id: '/_workspace/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof WorkspaceProductsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/people/$id': {
      id: '/_workspace/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof WorkspacePeopleIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/organizations/$id': {
      id: '/_workspace/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof WorkspaceOrganizationsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/bookings/$id': {
      id: '/_workspace/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof WorkspaceBookingsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/$id': {
      id: '/_workspace/availability/$id'
      path: '/availability/$id'
      fullPath: '/availability/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/pools/$id': {
      id: '/_workspace/resources/pools/$id'
      path: '/resources/pools/$id'
      fullPath: '/resources/pools/$id'
      preLoaderRoute: typeof WorkspaceResourcesPoolsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/assignments/$id': {
      id: '/_workspace/resources/assignments/$id'
      path: '/resources/assignments/$id'
      fullPath: '/resources/assignments/$id'
      preLoaderRoute: typeof WorkspaceResourcesAssignmentsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/resources/allocations/$id': {
      id: '/_workspace/resources/allocations/$id'
      path: '/resources/allocations/$id'
      fullPath: '/resources/allocations/$id'
      preLoaderRoute: typeof WorkspaceResourcesAllocationsIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/finance/invoices/$id': {
      id: '/_workspace/finance/invoices/$id'
      path: '/finance/invoices/$id'
      fullPath: '/finance/invoices/$id'
      preLoaderRoute: typeof WorkspaceFinanceInvoicesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/start-times/$id': {
      id: '/_workspace/availability/start-times/$id'
      path: '/availability/start-times/$id'
      fullPath: '/availability/start-times/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityStartTimesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/availability/rules/$id': {
      id: '/_workspace/availability/rules/$id'
      path: '/availability/rules/$id'
      fullPath: '/availability/rules/$id'
      preLoaderRoute: typeof WorkspaceAvailabilityRulesIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authAcceptInviteRoute: typeof authAcceptInviteRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authAcceptInviteRoute: authAcceptInviteRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOnboardingRoute: authOnboardingRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsChannelsRoute: typeof WorkspaceSettingsChannelsRoute
  WorkspaceSettingsPriceCatalogsRoute: typeof WorkspaceSettingsPriceCatalogsRoute
  WorkspaceSettingsPricingCategoriesRoute: typeof WorkspaceSettingsPricingCategoriesRoute
  WorkspaceSettingsProductTagsRoute: typeof WorkspaceSettingsProductTagsRoute
  WorkspaceSettingsProductTypesRoute: typeof WorkspaceSettingsProductTypesRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsChannelsRoute: WorkspaceSettingsChannelsRoute,
    WorkspaceSettingsPriceCatalogsRoute: WorkspaceSettingsPriceCatalogsRoute,
    WorkspaceSettingsPricingCategoriesRoute:
      WorkspaceSettingsPricingCategoriesRoute,
    WorkspaceSettingsProductTagsRoute: WorkspaceSettingsProductTagsRoute,
    WorkspaceSettingsProductTypesRoute: WorkspaceSettingsProductTypesRoute,
    WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceAvailabilityIdRoute: typeof WorkspaceAvailabilityIdRoute
  WorkspaceBookingsIdRoute: typeof WorkspaceBookingsIdRoute
  WorkspaceOrganizationsIdRoute: typeof WorkspaceOrganizationsIdRoute
  WorkspacePeopleIdRoute: typeof WorkspacePeopleIdRoute
  WorkspaceProductsIdRoute: typeof WorkspaceProductsIdRoute
  WorkspaceProductsCategoriesRoute: typeof WorkspaceProductsCategoriesRoute
  WorkspaceResourcesIdRoute: typeof WorkspaceResourcesIdRoute
  WorkspaceSuppliersIdRoute: typeof WorkspaceSuppliersIdRoute
  WorkspaceAvailabilityIndexRoute: typeof WorkspaceAvailabilityIndexRoute
  WorkspaceBookingsIndexRoute: typeof WorkspaceBookingsIndexRoute
  WorkspaceFinanceIndexRoute: typeof WorkspaceFinanceIndexRoute
  WorkspaceOrganizationsIndexRoute: typeof WorkspaceOrganizationsIndexRoute
  WorkspacePeopleIndexRoute: typeof WorkspacePeopleIndexRoute
  WorkspaceProductsIndexRoute: typeof WorkspaceProductsIndexRoute
  WorkspaceResourcesIndexRoute: typeof WorkspaceResourcesIndexRoute
  WorkspaceSuppliersIndexRoute: typeof WorkspaceSuppliersIndexRoute
  WorkspaceAvailabilityRulesIdRoute: typeof WorkspaceAvailabilityRulesIdRoute
  WorkspaceAvailabilityStartTimesIdRoute: typeof WorkspaceAvailabilityStartTimesIdRoute
  WorkspaceFinanceInvoicesIdRoute: typeof WorkspaceFinanceInvoicesIdRoute
  WorkspaceResourcesAllocationsIdRoute: typeof WorkspaceResourcesAllocationsIdRoute
  WorkspaceResourcesAssignmentsIdRoute: typeof WorkspaceResourcesAssignmentsIdRoute
  WorkspaceResourcesPoolsIdRoute: typeof WorkspaceResourcesPoolsIdRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceAvailabilityIdRoute: WorkspaceAvailabilityIdRoute,
  WorkspaceBookingsIdRoute: WorkspaceBookingsIdRoute,
  WorkspaceOrganizationsIdRoute: WorkspaceOrganizationsIdRoute,
  WorkspacePeopleIdRoute: WorkspacePeopleIdRoute,
  WorkspaceProductsIdRoute: WorkspaceProductsIdRoute,
  WorkspaceProductsCategoriesRoute: WorkspaceProductsCategoriesRoute,
  WorkspaceResourcesIdRoute: WorkspaceResourcesIdRoute,
  WorkspaceSuppliersIdRoute: WorkspaceSuppliersIdRoute,
  WorkspaceAvailabilityIndexRoute: WorkspaceAvailabilityIndexRoute,
  WorkspaceBookingsIndexRoute: WorkspaceBookingsIndexRoute,
  WorkspaceFinanceIndexRoute: WorkspaceFinanceIndexRoute,
  WorkspaceOrganizationsIndexRoute: WorkspaceOrganizationsIndexRoute,
  WorkspacePeopleIndexRoute: WorkspacePeopleIndexRoute,
  WorkspaceProductsIndexRoute: WorkspaceProductsIndexRoute,
  WorkspaceResourcesIndexRoute: WorkspaceResourcesIndexRoute,
  WorkspaceSuppliersIndexRoute: WorkspaceSuppliersIndexRoute,
  WorkspaceAvailabilityRulesIdRoute: WorkspaceAvailabilityRulesIdRoute,
  WorkspaceAvailabilityStartTimesIdRoute:
    WorkspaceAvailabilityStartTimesIdRoute,
  WorkspaceFinanceInvoicesIdRoute: WorkspaceFinanceInvoicesIdRoute,
  WorkspaceResourcesAllocationsIdRoute: WorkspaceResourcesAllocationsIdRoute,
  WorkspaceResourcesAssignmentsIdRoute: WorkspaceResourcesAssignmentsIdRoute,
  WorkspaceResourcesPoolsIdRoute: WorkspaceResourcesPoolsIdRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
