import type { Module } from "@voyantjs/core"
import type { HonoModule } from "@voyantjs/hono/module"

import { distributionRoutes } from "./routes.js"
import { distributionService } from "./service.js"

export type { DistributionRoutes } from "./routes.js"

export const distributionModule: Module = {
  name: "distribution",
}

export const distributionHonoModule: HonoModule = {
  module: distributionModule,
  routes: distributionRoutes,
}

export { distributionBookingExtension } from "./booking-extension.js"
export type {
  Channel,
  ChannelBookingLink,
  ChannelCommissionRule,
  ChannelContactProjection,
  ChannelContract,
  ChannelInventoryAllotment,
  ChannelInventoryAllotmentTarget,
  ChannelInventoryReleaseExecution,
  ChannelInventoryReleaseRule,
  ChannelProductMapping,
  ChannelReconciliationItem,
  ChannelReconciliationPolicy,
  ChannelReconciliationRun,
  ChannelReleaseSchedule,
  ChannelRemittanceException,
  ChannelSettlementApproval,
  ChannelSettlementItem,
  ChannelSettlementPolicy,
  ChannelSettlementRun,
  ChannelWebhookEvent,
  NewChannel,
  NewChannelBookingLink,
  NewChannelCommissionRule,
  NewChannelContactProjection,
  NewChannelContract,
  NewChannelInventoryAllotment,
  NewChannelInventoryAllotmentTarget,
  NewChannelInventoryReleaseExecution,
  NewChannelInventoryReleaseRule,
  NewChannelProductMapping,
  NewChannelReconciliationItem,
  NewChannelReconciliationPolicy,
  NewChannelReconciliationRun,
  NewChannelReleaseSchedule,
  NewChannelRemittanceException,
  NewChannelSettlementApproval,
  NewChannelSettlementItem,
  NewChannelSettlementPolicy,
  NewChannelSettlementRun,
  NewChannelWebhookEvent,
} from "./schema.js"
export {
  channelBookingLinks,
  channelCommissionRules,
  channelContactProjections,
  channelContracts,
  channelInventoryAllotments,
  channelInventoryAllotmentTargets,
  channelInventoryReleaseExecutions,
  channelInventoryReleaseRules,
  channelProductMappings,
  channelReconciliationItems,
  channelReconciliationPolicies,
  channelReconciliationPolicyFrequencyEnum,
  channelReconciliationRuns,
  channelReleaseScheduleKindEnum,
  channelReleaseSchedules,
  channelRemittanceExceptionStatusEnum,
  channelRemittanceExceptions,
  channelSettlementApprovalStatusEnum,
  channelSettlementApprovals,
  channelSettlementItems,
  channelSettlementPolicies,
  channelSettlementPolicyFrequencyEnum,
  channelSettlementRuns,
  channels,
  channelWebhookEvents,
} from "./schema.js"
export {
  channelBookingLinkListQuerySchema,
  channelCommissionRuleListQuerySchema,
  channelContractListQuerySchema,
  channelInventoryAllotmentListQuerySchema,
  channelInventoryAllotmentTargetListQuerySchema,
  channelInventoryReleaseExecutionListQuerySchema,
  channelInventoryReleaseRuleListQuerySchema,
  channelListQuerySchema,
  channelProductMappingListQuerySchema,
  channelReconciliationItemListQuerySchema,
  channelReconciliationPolicyFrequencySchema,
  channelReconciliationPolicyListQuerySchema,
  channelReconciliationRunListQuerySchema,
  channelReleaseScheduleKindSchema,
  channelReleaseScheduleListQuerySchema,
  channelRemittanceExceptionListQuerySchema,
  channelRemittanceExceptionStatusSchema,
  channelSettlementApprovalListQuerySchema,
  channelSettlementApprovalStatusSchema,
  channelSettlementItemListQuerySchema,
  channelSettlementPolicyFrequencySchema,
  channelSettlementPolicyListQuerySchema,
  channelSettlementRunListQuerySchema,
  channelWebhookEventListQuerySchema,
  insertChannelBookingLinkSchema,
  insertChannelCommissionRuleSchema,
  insertChannelContractSchema,
  insertChannelInventoryAllotmentSchema,
  insertChannelInventoryAllotmentTargetSchema,
  insertChannelInventoryReleaseExecutionSchema,
  insertChannelInventoryReleaseRuleSchema,
  insertChannelProductMappingSchema,
  insertChannelReconciliationItemSchema,
  insertChannelReconciliationPolicySchema,
  insertChannelReconciliationRunSchema,
  insertChannelReleaseScheduleSchema,
  insertChannelRemittanceExceptionSchema,
  insertChannelSchema,
  insertChannelSettlementApprovalSchema,
  insertChannelSettlementItemSchema,
  insertChannelSettlementPolicySchema,
  insertChannelSettlementRunSchema,
  insertChannelWebhookEventSchema,
  updateChannelBookingLinkSchema,
  updateChannelCommissionRuleSchema,
  updateChannelContractSchema,
  updateChannelInventoryAllotmentSchema,
  updateChannelInventoryAllotmentTargetSchema,
  updateChannelInventoryReleaseExecutionSchema,
  updateChannelInventoryReleaseRuleSchema,
  updateChannelProductMappingSchema,
  updateChannelReconciliationItemSchema,
  updateChannelReconciliationPolicySchema,
  updateChannelReconciliationRunSchema,
  updateChannelReleaseScheduleSchema,
  updateChannelRemittanceExceptionSchema,
  updateChannelSchema,
  updateChannelSettlementApprovalSchema,
  updateChannelSettlementItemSchema,
  updateChannelSettlementPolicySchema,
  updateChannelSettlementRunSchema,
  updateChannelWebhookEventSchema,
} from "./validation.js"
export { distributionService }
